/**
 * Generate German Course Seed Data
 * 200 Lessons: 2 Levels (A0, A1) x 4 Skills x 25 Lessons each
 */
const fs = require('fs');
const path = require('path');

const languageCode = 'de';
const levels = ['A0', 'A1'];
const skills = ['listening', 'speaking', 'reading', 'writing'];

const a0_topics = [
    { title: 'Greetings & Goodbyes', trans: 'Begrüßungen & Abschiede', visual: '👋' },
    { title: 'Numbers 1-10', trans: 'Zahlen 1-10', visual: '🔢' },
    { title: 'Basic Colors', trans: 'Grundfarben', visual: '🎨' },
    { title: 'My Family', trans: 'Meine Familie', visual: '👨‍👩‍👧‍👦' },
    { title: 'Pets', trans: 'Haustiere', visual: '🐶' },
    { title: 'Fruits', trans: 'Früchte', visual: '🍎' },
    { title: 'Body Parts', trans: 'Körperteile', visual: '👃' },
    { title: 'Emotions', trans: 'Gefühle', visual: '😊' },
    { title: 'At Home', trans: 'Zu Hause', visual: '🏠' },
    { title: 'Action Verbs', trans: 'Aktionsverben', visual: '🏃' },
    { title: 'Day & Night', trans: 'Tag & Nacht', visual: '🌞' },
    { title: 'Clothes', trans: 'Kleidung', visual: '👕' },
    { title: 'Transport', trans: 'Transport', visual: '🚗' },
    { title: 'Shapes', trans: 'Formen', visual: '📐' },
    { title: 'Nature', trans: 'Natur', visual: '🌳' },
    { title: 'Drinks', trans: 'Getränke', visual: '🥛' },
    { title: 'School Items', trans: 'Schulsachen', visual: '✏️' },
    { title: 'Weather', trans: 'Wetter', visual: '☁️' },
    { title: 'Directions', trans: 'Richtungen', visual: '⬅️' },
    { title: 'Sizes', trans: 'Größen', visual: '🐘' },
    { title: 'Numbers 11-20', trans: 'Zahlen 11-20', visual: '🔟' },
    { title: 'More Colors', trans: 'Mehr Farben', visual: '🌈' },
    { title: 'Wild Animals', trans: 'Wildtiere', visual: '🦁' },
    { title: 'More Actions', trans: 'Mehr Aktionen', visual: '💃' },
    { title: 'A0 Review', trans: 'A0 Wiederholung', visual: '🎓' }
];

const a1_topics = [
    { title: 'Introducing Yourself', trans: 'Sich vorstellen', visual: '🤝' },
    { title: 'Numbers to 100', trans: 'Zahlen bis 100', visual: '📊' },
    { title: 'Daily Routine 1', trans: 'Tagesablauf 1', visual: '⏰' },
    { title: 'Daily Routine 2', trans: 'Tagesablauf 2', visual: '🌙' },
    { title: 'In the Kitchen', trans: 'In der Küche', visual: '🍳' },
    { title: 'At the Supermarket', trans: 'Im Supermarkt', visual: '🛒' },
    { title: 'Hobbies', trans: 'Hobbies', visual: '🎸' },
    { title: 'My Apartment', trans: 'Meine Wohnung', visual: '🛋️' },
    { title: 'Days of the Week', trans: 'Wochentage', visual: '📅' },
    { title: 'Months & Seasons', trans: 'Monate & Jahreszeiten', visual: '❄️' },
    { title: 'Extreme Weather', trans: 'Extremes Wetter', visual: '⛈️' },
    { title: 'At the Restaurant', trans: 'Im Restaurant', visual: '🍴' },
    { title: 'At the Doctor', trans: 'Beim Arzt', visual: '🏥' },
    { title: 'Shopping for Clothes', trans: 'Kleidung kaufen', visual: '🛍️' },
    { title: 'Jobs', trans: 'Berufe', visual: '👷' },
    { title: 'My City', trans: 'Meine Stadt', visual: '🏙️' },
    { title: 'Telling Time', trans: 'Die Uhrzeit', visual: '⌚' },
    { title: 'Human Body', trans: 'Der menschliche Körper', visual: '🧠' },
    { title: 'Travel & Holidays', trans: 'Reisen & Urlaub', visual: '✈️' },
    { title: 'Sports', trans: 'Sport', visual: '⚽' },
    { title: 'Music', trans: 'Musik', visual: '🎶' },
    { title: 'Technology', trans: 'Technologie', visual: '💻' },
    { title: 'Festivals', trans: 'Feste', visual: '🎉' },
    { title: 'Giving Directions', trans: 'Wegbeschreibung', visual: '🗺️' },
    { title: 'A1 Final Review', trans: 'A1 Abschlusswiederholung', visual: '🏆' }
];

const topics = { 'A0': a0_topics, 'A1': a1_topics };

let sql = `-- German Comprehensive Course Seed Data
-- 200 Lessons: A0-A1 Level, All Skills
-- Generated by script

USE lingospark;

-- Ensure German is enabled and levels are updated
UPDATE languages SET enabled = TRUE, name = 'German', course_title = 'Speak German' WHERE code = 'de';
INSERT IGNORE INTO languages (code, name, course_title, enabled) VALUES ('de', 'German', 'Speak German', TRUE);

`;

function escape(str) {
    if (!str) return 'NULL';
    return "'" + str.replace(/'/g, "''") + "'";
}

for (const level of levels) {
    for (const skill of skills) {
        for (let i = 0; i < 25; i++) {
            const topic = topics[level][i];
            const title = topic.trans;
            const title_trans = topic.title;
            const description = `Lerne etwas über ${topic.trans}`;
            const description_trans = `Learn about ${topic.title}`;
            
            // Create Tutorial
            const tutorial = [
                { visual: topic.visual, title: `Willkommen zu ${title}!`, text: `Hier lernst du alles über ${title}.` },
                { visual: '📖', title: 'Schritt 1', text: `Schau dir die Bilder genau an.` },
                { visual: '🔊', title: 'Schritt 2', text: `Hör gut zu und sprich nach.` }
            ];

            // Create Exercises based on skill
            const content = {
                tutorial: tutorial,
                type: '',
                instructions: '',
                exercises: []
            };

            if (skill === 'listening') {
                content.type = 'listen_and_choose';
                content.instructions = 'Höre zu und wähle das richtige Bild.';
                content.exercises = [
                    { prompt: `Hallo!`, options: ['👋', '🏃', '🍎', '🚗'], correct: 0, hint: 'Eine Begrüßung' },
                    { prompt: title, options: [topic.visual, '🍎', '🚗', '🏠'], correct: 0, hint: `Denke an ${title}` },
                    { prompt: 'Guten Morgen!', options: ['☀️', '🌙', '💤', '🍕'], correct: 0, hint: 'Am Anfang des Tages' },
                    { prompt: 'Tausend Dank!', options: ['🙏', '😡', '😴', '🚲'], correct: 0, hint: 'Höfliche Antwort' },
                    { prompt: 'Auf Wiedersehen!', options: ['👋', '🤝', '🏃', '🛏️'], correct: 0, hint: 'Wenn man geht' }
                ];
            } else if (skill === 'speaking') {
                content.type = 'speak_and_compare';
                content.instructions = 'Sprich den Satz laut aus.';
                content.exercises = [
                    { prompt: title, expected: title.toLowerCase(), hint: 'Sag es deutlich' },
                    { prompt: 'Ich lerne Deutsch.', expected: 'ich lerne deutsch', hint: 'Satz sprechen' },
                    { prompt: 'Wie geht es dir?', expected: 'wie geht es dir', hint: 'Jemanden fragen' },
                    { prompt: 'Danke!', expected: 'danke', hint: 'Einfach danke sagen' },
                    { prompt: 'Tschüss!', expected: 'tschüss', hint: 'Sich verabschieden' }
                ];
            } else if (skill === 'reading') {
                content.type = 'read_and_choose';
                content.instructions = 'Lies den Satz und wähle die Antwort.';
                content.exercises = [
                    { sentence: `Das ist ${title}.`, question: `Was ist das?`, options: [title, 'Eine Frucht', 'Ein Auto', 'Ein Haus'], correct: 0, hint: 'Lies genau' },
                    { sentence: 'Der Himmel ist blau.', question: 'Welche Farbe hat der Himmel?', options: ['Blau', 'Grün', 'Rot', 'Gelb'], correct: 0, hint: 'Farben erkennen' },
                    { sentence: 'Ich habe einen Hund.', question: 'Was habe ich?', options: ['Hund', 'Katze', 'Auto', 'Apfel'], correct: 0, hint: 'Tiernamen' },
                    { sentence: 'Papa kocht Suppe.', question: 'Wer kocht?', options: ['Papa', 'Mama', 'Opa', 'Ich'], correct: 0, hint: 'Familie' },
                    { sentence: 'Eis ist kalt.', question: 'Wie ist das Eis?', options: ['Kalt', 'Heiß', 'Scharf', 'Süß'], correct: 1, hint: 'Eigenschaften' }
                ];
            } else if (skill === 'writing') {
                content.type = 'type_word';
                content.instructions = 'Tippe das Wort richtig.';
                content.exercises = [
                    { prompt: title, expected: title.toLowerCase(), hint: 'Buchstabiere vorsichtig' },
                    { prompt: 'Halle', expected: 'hallo', hint: 'Korrigiere den Fehler' },
                    { prompt: 'Apfel', expected: 'apfel', hint: 'Tippe die Frucht' },
                    { prompt: 'Katze', expected: 'katze', hint: 'Tippe das Tier' },
                    { prompt: 'Sonne', expected: 'sonne', hint: 'Tippe den Himmelskörper' }
                ];
            }

            // Pad exercises to at least 5
            while (content.exercises.length < 5) {
                content.exercises.push(JSON.parse(JSON.stringify(content.exercises[0])));
            }

            const contentStr = JSON.stringify(content);
            
            sql += `INSERT INTO lessons (language_code, cefr_level, skill, title, title_translation, description, description_translation, content, order_index) VALUES\n`;
            sql += `('de', '${level}', '${skill}', ${escape(title)}, ${escape(title_trans)}, ${escape(description)}, ${escape(description_trans)}, ${escape(contentStr)}, ${i + 1});\n\n`;
        }
    }
}

fs.writeFileSync(path.join(__dirname, '../db/seed_german_comprehensive.sql'), sql);
console.log('Generated 200 lessons in seed_german_comprehensive.sql');
