-- German Foundational Course (ABC) Comprehensive
USE lingospark;

-- Clear previous A0 lessons
DELETE FROM lessons WHERE language_code = 'de' AND cefr_level = 'A0';

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: A & B', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"}],"exercises":[{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"B","options":["🐻","🍎","🐱","🚗"],"correct":0},{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 1);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: A & B', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"}],"exercises":[{"prompt":"Apfel","expected":"apfel"},{"prompt":"Bär","expected":"bär"},{"prompt":"Apfel","expected":"apfel"},{"prompt":"Apfel","expected":"apfel"},{"prompt":"Apfel","expected":"apfel"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 1);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: A & B', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"}],"exercises":[{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0},{"sentence":"🐻","question":"Pick the name","options":["Bär","Apple","Car","Table"],"correct":0},{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0},{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0},{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 1);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: A & B', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"}],"exercises":[{"prompt":"🍎","expected":"apfel"},{"prompt":"🐻","expected":"bär"},{"prompt":"🍎","expected":"apfel"},{"prompt":"🍎","expected":"apfel"},{"prompt":"🍎","expected":"apfel"}],"type":"type_word","instructions":"Type the word."}', 1);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: C & D', 'Intro for beginners', '{"tutorial":[{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"}],"exercises":[{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0},{"prompt":"D","options":["🐉","🍎","🐱","🚗"],"correct":0},{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0},{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0},{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 2);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: C & D', 'Intro for beginners', '{"tutorial":[{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"}],"exercises":[{"prompt":"Clown","expected":"clown"},{"prompt":"Drache","expected":"drache"},{"prompt":"Clown","expected":"clown"},{"prompt":"Clown","expected":"clown"},{"prompt":"Clown","expected":"clown"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 2);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: C & D', 'Intro for beginners', '{"tutorial":[{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"}],"exercises":[{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0},{"sentence":"🐉","question":"Pick the name","options":["Drache","Apple","Car","Table"],"correct":0},{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0},{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0},{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 2);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: C & D', 'Intro for beginners', '{"tutorial":[{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"}],"exercises":[{"prompt":"🤡","expected":"clown"},{"prompt":"🐉","expected":"drache"},{"prompt":"🤡","expected":"clown"},{"prompt":"🤡","expected":"clown"},{"prompt":"🤡","expected":"clown"}],"type":"type_word","instructions":"Type the word."}', 2);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: E & F', 'Intro for beginners', '{"tutorial":[{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"},{"visual":"🐟","title":"F","text":"Fisch (Fish). Sounds like: eff"}],"exercises":[{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0},{"prompt":"F","options":["🐟","🍎","🐱","🚗"],"correct":0},{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0},{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0},{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 3);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: E & F', 'Intro for beginners', '{"tutorial":[{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"},{"visual":"🐟","title":"F","text":"Fisch (Fish). Sounds like: eff"}],"exercises":[{"prompt":"Elefant","expected":"elefant"},{"prompt":"Fisch","expected":"fisch"},{"prompt":"Elefant","expected":"elefant"},{"prompt":"Elefant","expected":"elefant"},{"prompt":"Elefant","expected":"elefant"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 3);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: E & F', 'Intro for beginners', '{"tutorial":[{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"},{"visual":"🐟","title":"F","text":"Fisch (Fish). Sounds like: eff"}],"exercises":[{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0},{"sentence":"🐟","question":"Pick the name","options":["Fisch","Apple","Car","Table"],"correct":0},{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0},{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0},{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 3);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: E & F', 'Intro for beginners', '{"tutorial":[{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"},{"visual":"🐟","title":"F","text":"Fisch (Fish). Sounds like: eff"}],"exercises":[{"prompt":"🐘","expected":"elefant"},{"prompt":"🐟","expected":"fisch"},{"prompt":"🐘","expected":"elefant"},{"prompt":"🐘","expected":"elefant"},{"prompt":"🐘","expected":"elefant"}],"type":"type_word","instructions":"Type the word."}', 3);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: G & H', 'Intro for beginners', '{"tutorial":[{"visual":"🦒","title":"G","text":"Giraffe (Giraffe). Sounds like: geh"},{"visual":"🏠","title":"H","text":"Haus (House). Sounds like: hah"}],"exercises":[{"prompt":"G","options":["🦒","🍎","🐱","🚗"],"correct":0},{"prompt":"H","options":["🏠","🍎","🐱","🚗"],"correct":0},{"prompt":"G","options":["🦒","🍎","🐱","🚗"],"correct":0},{"prompt":"G","options":["🦒","🍎","🐱","🚗"],"correct":0},{"prompt":"G","options":["🦒","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 4);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: G & H', 'Intro for beginners', '{"tutorial":[{"visual":"🦒","title":"G","text":"Giraffe (Giraffe). Sounds like: geh"},{"visual":"🏠","title":"H","text":"Haus (House). Sounds like: hah"}],"exercises":[{"prompt":"Giraffe","expected":"giraffe"},{"prompt":"Haus","expected":"haus"},{"prompt":"Giraffe","expected":"giraffe"},{"prompt":"Giraffe","expected":"giraffe"},{"prompt":"Giraffe","expected":"giraffe"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 4);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: G & H', 'Intro for beginners', '{"tutorial":[{"visual":"🦒","title":"G","text":"Giraffe (Giraffe). Sounds like: geh"},{"visual":"🏠","title":"H","text":"Haus (House). Sounds like: hah"}],"exercises":[{"sentence":"🦒","question":"Pick the name","options":["Giraffe","Apple","Car","Table"],"correct":0},{"sentence":"🏠","question":"Pick the name","options":["Haus","Apple","Car","Table"],"correct":0},{"sentence":"🦒","question":"Pick the name","options":["Giraffe","Apple","Car","Table"],"correct":0},{"sentence":"🦒","question":"Pick the name","options":["Giraffe","Apple","Car","Table"],"correct":0},{"sentence":"🦒","question":"Pick the name","options":["Giraffe","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 4);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: G & H', 'Intro for beginners', '{"tutorial":[{"visual":"🦒","title":"G","text":"Giraffe (Giraffe). Sounds like: geh"},{"visual":"🏠","title":"H","text":"Haus (House). Sounds like: hah"}],"exercises":[{"prompt":"🦒","expected":"giraffe"},{"prompt":"🏠","expected":"haus"},{"prompt":"🦒","expected":"giraffe"},{"prompt":"🦒","expected":"giraffe"},{"prompt":"🦒","expected":"giraffe"}],"type":"type_word","instructions":"Type the word."}', 4);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: I & J', 'Intro for beginners', '{"tutorial":[{"visual":"🦔","title":"I","text":"Igel (Hedgehog). Sounds like: ee"},{"visual":"🧥","title":"J","text":"Jacke (Jacket). Sounds like: yot"}],"exercises":[{"prompt":"I","options":["🦔","🍎","🐱","🚗"],"correct":0},{"prompt":"J","options":["🧥","🍎","🐱","🚗"],"correct":0},{"prompt":"I","options":["🦔","🍎","🐱","🚗"],"correct":0},{"prompt":"I","options":["🦔","🍎","🐱","🚗"],"correct":0},{"prompt":"I","options":["🦔","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 5);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: I & J', 'Intro for beginners', '{"tutorial":[{"visual":"🦔","title":"I","text":"Igel (Hedgehog). Sounds like: ee"},{"visual":"🧥","title":"J","text":"Jacke (Jacket). Sounds like: yot"}],"exercises":[{"prompt":"Igel","expected":"igel"},{"prompt":"Jacke","expected":"jacke"},{"prompt":"Igel","expected":"igel"},{"prompt":"Igel","expected":"igel"},{"prompt":"Igel","expected":"igel"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 5);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: I & J', 'Intro for beginners', '{"tutorial":[{"visual":"🦔","title":"I","text":"Igel (Hedgehog). Sounds like: ee"},{"visual":"🧥","title":"J","text":"Jacke (Jacket). Sounds like: yot"}],"exercises":[{"sentence":"🦔","question":"Pick the name","options":["Igel","Apple","Car","Table"],"correct":0},{"sentence":"🧥","question":"Pick the name","options":["Jacke","Apple","Car","Table"],"correct":0},{"sentence":"🦔","question":"Pick the name","options":["Igel","Apple","Car","Table"],"correct":0},{"sentence":"🦔","question":"Pick the name","options":["Igel","Apple","Car","Table"],"correct":0},{"sentence":"🦔","question":"Pick the name","options":["Igel","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 5);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: I & J', 'Intro for beginners', '{"tutorial":[{"visual":"🦔","title":"I","text":"Igel (Hedgehog). Sounds like: ee"},{"visual":"🧥","title":"J","text":"Jacke (Jacket). Sounds like: yot"}],"exercises":[{"prompt":"🦔","expected":"igel"},{"prompt":"🧥","expected":"jacke"},{"prompt":"🦔","expected":"igel"},{"prompt":"🦔","expected":"igel"},{"prompt":"🦔","expected":"igel"}],"type":"type_word","instructions":"Type the word."}', 5);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: K & L', 'Intro for beginners', '{"tutorial":[{"visual":"🐱","title":"K","text":"Katze (Cat). Sounds like: kah"},{"visual":"🦁","title":"L","text":"Löwe (Lion). Sounds like: ell"}],"exercises":[{"prompt":"K","options":["🐱","🍎","🐱","🚗"],"correct":0},{"prompt":"L","options":["🦁","🍎","🐱","🚗"],"correct":0},{"prompt":"K","options":["🐱","🍎","🐱","🚗"],"correct":0},{"prompt":"K","options":["🐱","🍎","🐱","🚗"],"correct":0},{"prompt":"K","options":["🐱","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 6);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: K & L', 'Intro for beginners', '{"tutorial":[{"visual":"🐱","title":"K","text":"Katze (Cat). Sounds like: kah"},{"visual":"🦁","title":"L","text":"Löwe (Lion). Sounds like: ell"}],"exercises":[{"prompt":"Katze","expected":"katze"},{"prompt":"Löwe","expected":"löwe"},{"prompt":"Katze","expected":"katze"},{"prompt":"Katze","expected":"katze"},{"prompt":"Katze","expected":"katze"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 6);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: K & L', 'Intro for beginners', '{"tutorial":[{"visual":"🐱","title":"K","text":"Katze (Cat). Sounds like: kah"},{"visual":"🦁","title":"L","text":"Löwe (Lion). Sounds like: ell"}],"exercises":[{"sentence":"🐱","question":"Pick the name","options":["Katze","Apple","Car","Table"],"correct":0},{"sentence":"🦁","question":"Pick the name","options":["Löwe","Apple","Car","Table"],"correct":0},{"sentence":"🐱","question":"Pick the name","options":["Katze","Apple","Car","Table"],"correct":0},{"sentence":"🐱","question":"Pick the name","options":["Katze","Apple","Car","Table"],"correct":0},{"sentence":"🐱","question":"Pick the name","options":["Katze","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 6);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: K & L', 'Intro for beginners', '{"tutorial":[{"visual":"🐱","title":"K","text":"Katze (Cat). Sounds like: kah"},{"visual":"🦁","title":"L","text":"Löwe (Lion). Sounds like: ell"}],"exercises":[{"prompt":"🐱","expected":"katze"},{"prompt":"🦁","expected":"löwe"},{"prompt":"🐱","expected":"katze"},{"prompt":"🐱","expected":"katze"},{"prompt":"🐱","expected":"katze"}],"type":"type_word","instructions":"Type the word."}', 6);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: M & N', 'Intro for beginners', '{"tutorial":[{"visual":"🐭","title":"M","text":"Maus (Mouse). Sounds like: emm"},{"visual":"👃","title":"N","text":"Nase (Nose). Sounds like: enn"}],"exercises":[{"prompt":"M","options":["🐭","🍎","🐱","🚗"],"correct":0},{"prompt":"N","options":["👃","🍎","🐱","🚗"],"correct":0},{"prompt":"M","options":["🐭","🍎","🐱","🚗"],"correct":0},{"prompt":"M","options":["🐭","🍎","🐱","🚗"],"correct":0},{"prompt":"M","options":["🐭","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 7);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: M & N', 'Intro for beginners', '{"tutorial":[{"visual":"🐭","title":"M","text":"Maus (Mouse). Sounds like: emm"},{"visual":"👃","title":"N","text":"Nase (Nose). Sounds like: enn"}],"exercises":[{"prompt":"Maus","expected":"maus"},{"prompt":"Nase","expected":"nase"},{"prompt":"Maus","expected":"maus"},{"prompt":"Maus","expected":"maus"},{"prompt":"Maus","expected":"maus"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 7);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: M & N', 'Intro for beginners', '{"tutorial":[{"visual":"🐭","title":"M","text":"Maus (Mouse). Sounds like: emm"},{"visual":"👃","title":"N","text":"Nase (Nose). Sounds like: enn"}],"exercises":[{"sentence":"🐭","question":"Pick the name","options":["Maus","Apple","Car","Table"],"correct":0},{"sentence":"👃","question":"Pick the name","options":["Nase","Apple","Car","Table"],"correct":0},{"sentence":"🐭","question":"Pick the name","options":["Maus","Apple","Car","Table"],"correct":0},{"sentence":"🐭","question":"Pick the name","options":["Maus","Apple","Car","Table"],"correct":0},{"sentence":"🐭","question":"Pick the name","options":["Maus","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 7);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: M & N', 'Intro for beginners', '{"tutorial":[{"visual":"🐭","title":"M","text":"Maus (Mouse). Sounds like: emm"},{"visual":"👃","title":"N","text":"Nase (Nose). Sounds like: enn"}],"exercises":[{"prompt":"🐭","expected":"maus"},{"prompt":"👃","expected":"nase"},{"prompt":"🐭","expected":"maus"},{"prompt":"🐭","expected":"maus"},{"prompt":"🐭","expected":"maus"}],"type":"type_word","instructions":"Type the word."}', 7);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: O & P', 'Intro for beginners', '{"tutorial":[{"visual":"👴","title":"O","text":"Opa (Grandpa). Sounds like: oh"},{"visual":"🐧","title":"P","text":"Pinguin (Penguin). Sounds like: peh"}],"exercises":[{"prompt":"O","options":["👴","🍎","🐱","🚗"],"correct":0},{"prompt":"P","options":["🐧","🍎","🐱","🚗"],"correct":0},{"prompt":"O","options":["👴","🍎","🐱","🚗"],"correct":0},{"prompt":"O","options":["👴","🍎","🐱","🚗"],"correct":0},{"prompt":"O","options":["👴","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 8);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: O & P', 'Intro for beginners', '{"tutorial":[{"visual":"👴","title":"O","text":"Opa (Grandpa). Sounds like: oh"},{"visual":"🐧","title":"P","text":"Pinguin (Penguin). Sounds like: peh"}],"exercises":[{"prompt":"Opa","expected":"opa"},{"prompt":"Pinguin","expected":"pinguin"},{"prompt":"Opa","expected":"opa"},{"prompt":"Opa","expected":"opa"},{"prompt":"Opa","expected":"opa"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 8);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: O & P', 'Intro for beginners', '{"tutorial":[{"visual":"👴","title":"O","text":"Opa (Grandpa). Sounds like: oh"},{"visual":"🐧","title":"P","text":"Pinguin (Penguin). Sounds like: peh"}],"exercises":[{"sentence":"👴","question":"Pick the name","options":["Opa","Apple","Car","Table"],"correct":0},{"sentence":"🐧","question":"Pick the name","options":["Pinguin","Apple","Car","Table"],"correct":0},{"sentence":"👴","question":"Pick the name","options":["Opa","Apple","Car","Table"],"correct":0},{"sentence":"👴","question":"Pick the name","options":["Opa","Apple","Car","Table"],"correct":0},{"sentence":"👴","question":"Pick the name","options":["Opa","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 8);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: O & P', 'Intro for beginners', '{"tutorial":[{"visual":"👴","title":"O","text":"Opa (Grandpa). Sounds like: oh"},{"visual":"🐧","title":"P","text":"Pinguin (Penguin). Sounds like: peh"}],"exercises":[{"prompt":"👴","expected":"opa"},{"prompt":"🐧","expected":"pinguin"},{"prompt":"👴","expected":"opa"},{"prompt":"👴","expected":"opa"},{"prompt":"👴","expected":"opa"}],"type":"type_word","instructions":"Type the word."}', 8);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: Q & R', 'Intro for beginners', '{"tutorial":[{"visual":"🪼","title":"Q","text":"Qualle (Jellyfish). Sounds like: koo"},{"visual":"🌈","title":"R","text":"Regenbogen (Rainbow). Sounds like: err"}],"exercises":[{"prompt":"Q","options":["🪼","🍎","🐱","🚗"],"correct":0},{"prompt":"R","options":["🌈","🍎","🐱","🚗"],"correct":0},{"prompt":"Q","options":["🪼","🍎","🐱","🚗"],"correct":0},{"prompt":"Q","options":["🪼","🍎","🐱","🚗"],"correct":0},{"prompt":"Q","options":["🪼","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 9);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: Q & R', 'Intro for beginners', '{"tutorial":[{"visual":"🪼","title":"Q","text":"Qualle (Jellyfish). Sounds like: koo"},{"visual":"🌈","title":"R","text":"Regenbogen (Rainbow). Sounds like: err"}],"exercises":[{"prompt":"Qualle","expected":"qualle"},{"prompt":"Regenbogen","expected":"regenbogen"},{"prompt":"Qualle","expected":"qualle"},{"prompt":"Qualle","expected":"qualle"},{"prompt":"Qualle","expected":"qualle"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 9);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: Q & R', 'Intro for beginners', '{"tutorial":[{"visual":"🪼","title":"Q","text":"Qualle (Jellyfish). Sounds like: koo"},{"visual":"🌈","title":"R","text":"Regenbogen (Rainbow). Sounds like: err"}],"exercises":[{"sentence":"🪼","question":"Pick the name","options":["Qualle","Apple","Car","Table"],"correct":0},{"sentence":"🌈","question":"Pick the name","options":["Regenbogen","Apple","Car","Table"],"correct":0},{"sentence":"🪼","question":"Pick the name","options":["Qualle","Apple","Car","Table"],"correct":0},{"sentence":"🪼","question":"Pick the name","options":["Qualle","Apple","Car","Table"],"correct":0},{"sentence":"🪼","question":"Pick the name","options":["Qualle","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 9);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: Q & R', 'Intro for beginners', '{"tutorial":[{"visual":"🪼","title":"Q","text":"Qualle (Jellyfish). Sounds like: koo"},{"visual":"🌈","title":"R","text":"Regenbogen (Rainbow). Sounds like: err"}],"exercises":[{"prompt":"🪼","expected":"qualle"},{"prompt":"🌈","expected":"regenbogen"},{"prompt":"🪼","expected":"qualle"},{"prompt":"🪼","expected":"qualle"},{"prompt":"🪼","expected":"qualle"}],"type":"type_word","instructions":"Type the word."}', 9);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: S & T', 'Intro for beginners', '{"tutorial":[{"visual":"☀️","title":"S","text":"Sonne (Sun). Sounds like: ess"},{"visual":"🐯","title":"T","text":"Tiger (Tiger). Sounds like: teh"}],"exercises":[{"prompt":"S","options":["☀️","🍎","🐱","🚗"],"correct":0},{"prompt":"T","options":["🐯","🍎","🐱","🚗"],"correct":0},{"prompt":"S","options":["☀️","🍎","🐱","🚗"],"correct":0},{"prompt":"S","options":["☀️","🍎","🐱","🚗"],"correct":0},{"prompt":"S","options":["☀️","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 10);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: S & T', 'Intro for beginners', '{"tutorial":[{"visual":"☀️","title":"S","text":"Sonne (Sun). Sounds like: ess"},{"visual":"🐯","title":"T","text":"Tiger (Tiger). Sounds like: teh"}],"exercises":[{"prompt":"Sonne","expected":"sonne"},{"prompt":"Tiger","expected":"tiger"},{"prompt":"Sonne","expected":"sonne"},{"prompt":"Sonne","expected":"sonne"},{"prompt":"Sonne","expected":"sonne"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 10);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: S & T', 'Intro for beginners', '{"tutorial":[{"visual":"☀️","title":"S","text":"Sonne (Sun). Sounds like: ess"},{"visual":"🐯","title":"T","text":"Tiger (Tiger). Sounds like: teh"}],"exercises":[{"sentence":"☀️","question":"Pick the name","options":["Sonne","Apple","Car","Table"],"correct":0},{"sentence":"🐯","question":"Pick the name","options":["Tiger","Apple","Car","Table"],"correct":0},{"sentence":"☀️","question":"Pick the name","options":["Sonne","Apple","Car","Table"],"correct":0},{"sentence":"☀️","question":"Pick the name","options":["Sonne","Apple","Car","Table"],"correct":0},{"sentence":"☀️","question":"Pick the name","options":["Sonne","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 10);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: S & T', 'Intro for beginners', '{"tutorial":[{"visual":"☀️","title":"S","text":"Sonne (Sun). Sounds like: ess"},{"visual":"🐯","title":"T","text":"Tiger (Tiger). Sounds like: teh"}],"exercises":[{"prompt":"☀️","expected":"sonne"},{"prompt":"🐯","expected":"tiger"},{"prompt":"☀️","expected":"sonne"},{"prompt":"☀️","expected":"sonne"},{"prompt":"☀️","expected":"sonne"}],"type":"type_word","instructions":"Type the word."}', 10);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: U & V', 'Intro for beginners', '{"tutorial":[{"visual":"⌚","title":"U","text":"Uhr (Clock). Sounds like: oo"},{"visual":"🐦","title":"V","text":"Vogel (Bird). Sounds like: fow"}],"exercises":[{"prompt":"U","options":["⌚","🍎","🐱","🚗"],"correct":0},{"prompt":"V","options":["🐦","🍎","🐱","🚗"],"correct":0},{"prompt":"U","options":["⌚","🍎","🐱","🚗"],"correct":0},{"prompt":"U","options":["⌚","🍎","🐱","🚗"],"correct":0},{"prompt":"U","options":["⌚","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 11);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: U & V', 'Intro for beginners', '{"tutorial":[{"visual":"⌚","title":"U","text":"Uhr (Clock). Sounds like: oo"},{"visual":"🐦","title":"V","text":"Vogel (Bird). Sounds like: fow"}],"exercises":[{"prompt":"Uhr","expected":"uhr"},{"prompt":"Vogel","expected":"vogel"},{"prompt":"Uhr","expected":"uhr"},{"prompt":"Uhr","expected":"uhr"},{"prompt":"Uhr","expected":"uhr"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 11);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: U & V', 'Intro for beginners', '{"tutorial":[{"visual":"⌚","title":"U","text":"Uhr (Clock). Sounds like: oo"},{"visual":"🐦","title":"V","text":"Vogel (Bird). Sounds like: fow"}],"exercises":[{"sentence":"⌚","question":"Pick the name","options":["Uhr","Apple","Car","Table"],"correct":0},{"sentence":"🐦","question":"Pick the name","options":["Vogel","Apple","Car","Table"],"correct":0},{"sentence":"⌚","question":"Pick the name","options":["Uhr","Apple","Car","Table"],"correct":0},{"sentence":"⌚","question":"Pick the name","options":["Uhr","Apple","Car","Table"],"correct":0},{"sentence":"⌚","question":"Pick the name","options":["Uhr","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 11);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: U & V', 'Intro for beginners', '{"tutorial":[{"visual":"⌚","title":"U","text":"Uhr (Clock). Sounds like: oo"},{"visual":"🐦","title":"V","text":"Vogel (Bird). Sounds like: fow"}],"exercises":[{"prompt":"⌚","expected":"uhr"},{"prompt":"🐦","expected":"vogel"},{"prompt":"⌚","expected":"uhr"},{"prompt":"⌚","expected":"uhr"},{"prompt":"⌚","expected":"uhr"}],"type":"type_word","instructions":"Type the word."}', 11);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: W & X', 'Intro for beginners', '{"tutorial":[{"visual":"🐋","title":"W","text":"Wal (Whale). Sounds like: veh"},{"visual":"🪗","title":"X","text":"Xylophon (Xylophone). Sounds like: iks"}],"exercises":[{"prompt":"W","options":["🐋","🍎","🐱","🚗"],"correct":0},{"prompt":"X","options":["🪗","🍎","🐱","🚗"],"correct":0},{"prompt":"W","options":["🐋","🍎","🐱","🚗"],"correct":0},{"prompt":"W","options":["🐋","🍎","🐱","🚗"],"correct":0},{"prompt":"W","options":["🐋","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 12);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: W & X', 'Intro for beginners', '{"tutorial":[{"visual":"🐋","title":"W","text":"Wal (Whale). Sounds like: veh"},{"visual":"🪗","title":"X","text":"Xylophon (Xylophone). Sounds like: iks"}],"exercises":[{"prompt":"Wal","expected":"wal"},{"prompt":"Xylophon","expected":"xylophon"},{"prompt":"Wal","expected":"wal"},{"prompt":"Wal","expected":"wal"},{"prompt":"Wal","expected":"wal"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 12);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: W & X', 'Intro for beginners', '{"tutorial":[{"visual":"🐋","title":"W","text":"Wal (Whale). Sounds like: veh"},{"visual":"🪗","title":"X","text":"Xylophon (Xylophone). Sounds like: iks"}],"exercises":[{"sentence":"🐋","question":"Pick the name","options":["Wal","Apple","Car","Table"],"correct":0},{"sentence":"🪗","question":"Pick the name","options":["Xylophon","Apple","Car","Table"],"correct":0},{"sentence":"🐋","question":"Pick the name","options":["Wal","Apple","Car","Table"],"correct":0},{"sentence":"🐋","question":"Pick the name","options":["Wal","Apple","Car","Table"],"correct":0},{"sentence":"🐋","question":"Pick the name","options":["Wal","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 12);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: W & X', 'Intro for beginners', '{"tutorial":[{"visual":"🐋","title":"W","text":"Wal (Whale). Sounds like: veh"},{"visual":"🪗","title":"X","text":"Xylophon (Xylophone). Sounds like: iks"}],"exercises":[{"prompt":"🐋","expected":"wal"},{"prompt":"🪗","expected":"xylophon"},{"prompt":"🐋","expected":"wal"},{"prompt":"🐋","expected":"wal"},{"prompt":"🐋","expected":"wal"}],"type":"type_word","instructions":"Type the word."}', 12);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'ABC: Y & Z', 'Intro for beginners', '{"tutorial":[{"visual":"🧘","title":"Y","text":"Yoga (Yoga). Sounds like: ypsilon"},{"visual":"🏁","title":"Z","text":"Zebra (Zebra). Sounds like: tsett"}],"exercises":[{"prompt":"Y","options":["🧘","🍎","🐱","🚗"],"correct":0},{"prompt":"Z","options":["🏁","🍎","🐱","🚗"],"correct":0},{"prompt":"Y","options":["🧘","🍎","🐱","🚗"],"correct":0},{"prompt":"Y","options":["🧘","🍎","🐱","🚗"],"correct":0},{"prompt":"Y","options":["🧘","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 13);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'ABC: Y & Z', 'Intro for beginners', '{"tutorial":[{"visual":"🧘","title":"Y","text":"Yoga (Yoga). Sounds like: ypsilon"},{"visual":"🏁","title":"Z","text":"Zebra (Zebra). Sounds like: tsett"}],"exercises":[{"prompt":"Yoga","expected":"yoga"},{"prompt":"Zebra","expected":"zebra"},{"prompt":"Yoga","expected":"yoga"},{"prompt":"Yoga","expected":"yoga"},{"prompt":"Yoga","expected":"yoga"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 13);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'ABC: Y & Z', 'Intro for beginners', '{"tutorial":[{"visual":"🧘","title":"Y","text":"Yoga (Yoga). Sounds like: ypsilon"},{"visual":"🏁","title":"Z","text":"Zebra (Zebra). Sounds like: tsett"}],"exercises":[{"sentence":"🧘","question":"Pick the name","options":["Yoga","Apple","Car","Table"],"correct":0},{"sentence":"🏁","question":"Pick the name","options":["Zebra","Apple","Car","Table"],"correct":0},{"sentence":"🧘","question":"Pick the name","options":["Yoga","Apple","Car","Table"],"correct":0},{"sentence":"🧘","question":"Pick the name","options":["Yoga","Apple","Car","Table"],"correct":0},{"sentence":"🧘","question":"Pick the name","options":["Yoga","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 13);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'ABC: Y & Z', 'Intro for beginners', '{"tutorial":[{"visual":"🧘","title":"Y","text":"Yoga (Yoga). Sounds like: ypsilon"},{"visual":"🏁","title":"Z","text":"Zebra (Zebra). Sounds like: tsett"}],"exercises":[{"prompt":"🧘","expected":"yoga"},{"prompt":"🏁","expected":"zebra"},{"prompt":"🧘","expected":"yoga"},{"prompt":"🧘","expected":"yoga"},{"prompt":"🧘","expected":"yoga"}],"type":"type_word","instructions":"Type the word."}', 13);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Special Letters', 'Intro for beginners', '{"tutorial":[{"visual":"🍎🍎","title":"Ä","text":"Äpfel (Apples). Sounds like: aeh"},{"visual":"🛢️","title":"Ö","text":"Öl (Oil). Sounds like: oeh"},{"visual":"🎁","title":"Ü","text":"Überraschung (Surprise). Sounds like: ueh"},{"visual":"🦶","title":"ß","text":"Fuß (Foot). Sounds like: ess-tsett"}],"exercises":[{"prompt":"Ä","options":["🍎🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"Ö","options":["🛢️","🍎","🐱","🚗"],"correct":0},{"prompt":"Ü","options":["🎁","🍎","🐱","🚗"],"correct":0},{"prompt":"ß","options":["🦶","🍎","🐱","🚗"],"correct":0},{"prompt":"Ä","options":["🍎🍎","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 14);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Special Letters', 'Intro for beginners', '{"tutorial":[{"visual":"🍎🍎","title":"Ä","text":"Äpfel (Apples). Sounds like: aeh"},{"visual":"🛢️","title":"Ö","text":"Öl (Oil). Sounds like: oeh"},{"visual":"🎁","title":"Ü","text":"Überraschung (Surprise). Sounds like: ueh"},{"visual":"🦶","title":"ß","text":"Fuß (Foot). Sounds like: ess-tsett"}],"exercises":[{"prompt":"Äpfel","expected":"äpfel"},{"prompt":"Öl","expected":"öl"},{"prompt":"Überraschung","expected":"überraschung"},{"prompt":"Fuß","expected":"fuß"},{"prompt":"Äpfel","expected":"äpfel"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 14);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Special Letters', 'Intro for beginners', '{"tutorial":[{"visual":"🍎🍎","title":"Ä","text":"Äpfel (Apples). Sounds like: aeh"},{"visual":"🛢️","title":"Ö","text":"Öl (Oil). Sounds like: oeh"},{"visual":"🎁","title":"Ü","text":"Überraschung (Surprise). Sounds like: ueh"},{"visual":"🦶","title":"ß","text":"Fuß (Foot). Sounds like: ess-tsett"}],"exercises":[{"sentence":"🍎🍎","question":"Pick the name","options":["Äpfel","Apple","Car","Table"],"correct":0},{"sentence":"🛢️","question":"Pick the name","options":["Öl","Apple","Car","Table"],"correct":0},{"sentence":"🎁","question":"Pick the name","options":["Überraschung","Apple","Car","Table"],"correct":0},{"sentence":"🦶","question":"Pick the name","options":["Fuß","Apple","Car","Table"],"correct":0},{"sentence":"🍎🍎","question":"Pick the name","options":["Äpfel","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 14);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Special Letters', 'Intro for beginners', '{"tutorial":[{"visual":"🍎🍎","title":"Ä","text":"Äpfel (Apples). Sounds like: aeh"},{"visual":"🛢️","title":"Ö","text":"Öl (Oil). Sounds like: oeh"},{"visual":"🎁","title":"Ü","text":"Überraschung (Surprise). Sounds like: ueh"},{"visual":"🦶","title":"ß","text":"Fuß (Foot). Sounds like: ess-tsett"}],"exercises":[{"prompt":"🍎🍎","expected":"äpfel"},{"prompt":"🛢️","expected":"öl"},{"prompt":"🎁","expected":"überraschung"},{"prompt":"🦶","expected":"fuß"},{"prompt":"🍎🍎","expected":"äpfel"}],"type":"type_word","instructions":"Type the word."}', 14);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Basics: Greetings', 'Intro for beginners', '{"tutorial":[{"visual":"👋","title":"Hallo","text":"Hallo (Hello)"},{"visual":"🙋","title":"Guten Tag","text":"Guten Tag (Good Day)"},{"visual":"🌙","title":"Gute Nacht","text":"Gute Nacht (Good Night)"},{"visual":"👋","title":"Tschüss","text":"Tschüss (Bye)"}],"exercises":[{"prompt":"Hallo","options":["👋","🍎","🐱","🚗"],"correct":0},{"prompt":"Guten Tag","options":["🙋","🍎","🐱","🚗"],"correct":0},{"prompt":"Gute Nacht","options":["🌙","🍎","🐱","🚗"],"correct":0},{"prompt":"Tschüss","options":["👋","🍎","🐱","🚗"],"correct":0},{"prompt":"Hallo","options":["👋","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 15);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Basics: Greetings', 'Intro for beginners', '{"tutorial":[{"visual":"👋","title":"Hallo","text":"Hallo (Hello)"},{"visual":"🙋","title":"Guten Tag","text":"Guten Tag (Good Day)"},{"visual":"🌙","title":"Gute Nacht","text":"Gute Nacht (Good Night)"},{"visual":"👋","title":"Tschüss","text":"Tschüss (Bye)"}],"exercises":[{"prompt":"Hallo","expected":"hallo"},{"prompt":"Guten Tag","expected":"guten tag"},{"prompt":"Gute Nacht","expected":"gute nacht"},{"prompt":"Tschüss","expected":"tschüss"},{"prompt":"Hallo","expected":"hallo"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 15);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Basics: Greetings', 'Intro for beginners', '{"tutorial":[{"visual":"👋","title":"Hallo","text":"Hallo (Hello)"},{"visual":"🙋","title":"Guten Tag","text":"Guten Tag (Good Day)"},{"visual":"🌙","title":"Gute Nacht","text":"Gute Nacht (Good Night)"},{"visual":"👋","title":"Tschüss","text":"Tschüss (Bye)"}],"exercises":[{"sentence":"👋","question":"Pick the name","options":["Hallo","Apple","Car","Table"],"correct":0},{"sentence":"🙋","question":"Pick the name","options":["Guten Tag","Apple","Car","Table"],"correct":0},{"sentence":"🌙","question":"Pick the name","options":["Gute Nacht","Apple","Car","Table"],"correct":0},{"sentence":"👋","question":"Pick the name","options":["Tschüss","Apple","Car","Table"],"correct":0},{"sentence":"👋","question":"Pick the name","options":["Hallo","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 15);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Basics: Greetings', 'Intro for beginners', '{"tutorial":[{"visual":"👋","title":"Hallo","text":"Hallo (Hello)"},{"visual":"🙋","title":"Guten Tag","text":"Guten Tag (Good Day)"},{"visual":"🌙","title":"Gute Nacht","text":"Gute Nacht (Good Night)"},{"visual":"👋","title":"Tschüss","text":"Tschüss (Bye)"}],"exercises":[{"prompt":"👋","expected":"hallo"},{"prompt":"🙋","expected":"guten tag"},{"prompt":"🌙","expected":"gute nacht"},{"prompt":"👋","expected":"tschüss"},{"prompt":"👋","expected":"hallo"}],"type":"type_word","instructions":"Type the word."}', 15);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Basics: Numbers 1-5', 'Intro for beginners', '{"tutorial":[{"visual":"1️⃣","title":"eins","text":"eins (one)"},{"visual":"2️⃣","title":"zwei","text":"zwei (two)"},{"visual":"3️⃣","title":"drei","text":"drei (three)"},{"visual":"4️⃣","title":"vier","text":"vier (four)"},{"visual":"5️⃣","title":"fünf","text":"fünf (five)"}],"exercises":[{"prompt":"eins","options":["1️⃣","🍎","🐱","🚗"],"correct":0},{"prompt":"zwei","options":["2️⃣","🍎","🐱","🚗"],"correct":0},{"prompt":"drei","options":["3️⃣","🍎","🐱","🚗"],"correct":0},{"prompt":"vier","options":["4️⃣","🍎","🐱","🚗"],"correct":0},{"prompt":"fünf","options":["5️⃣","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 16);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Basics: Numbers 1-5', 'Intro for beginners', '{"tutorial":[{"visual":"1️⃣","title":"eins","text":"eins (one)"},{"visual":"2️⃣","title":"zwei","text":"zwei (two)"},{"visual":"3️⃣","title":"drei","text":"drei (three)"},{"visual":"4️⃣","title":"vier","text":"vier (four)"},{"visual":"5️⃣","title":"fünf","text":"fünf (five)"}],"exercises":[{"prompt":"eins","expected":"eins"},{"prompt":"zwei","expected":"zwei"},{"prompt":"drei","expected":"drei"},{"prompt":"vier","expected":"vier"},{"prompt":"fünf","expected":"fünf"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 16);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Basics: Numbers 1-5', 'Intro for beginners', '{"tutorial":[{"visual":"1️⃣","title":"eins","text":"eins (one)"},{"visual":"2️⃣","title":"zwei","text":"zwei (two)"},{"visual":"3️⃣","title":"drei","text":"drei (three)"},{"visual":"4️⃣","title":"vier","text":"vier (four)"},{"visual":"5️⃣","title":"fünf","text":"fünf (five)"}],"exercises":[{"sentence":"1️⃣","question":"Pick the name","options":["eins","Apple","Car","Table"],"correct":0},{"sentence":"2️⃣","question":"Pick the name","options":["zwei","Apple","Car","Table"],"correct":0},{"sentence":"3️⃣","question":"Pick the name","options":["drei","Apple","Car","Table"],"correct":0},{"sentence":"4️⃣","question":"Pick the name","options":["vier","Apple","Car","Table"],"correct":0},{"sentence":"5️⃣","question":"Pick the name","options":["fünf","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 16);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Basics: Numbers 1-5', 'Intro for beginners', '{"tutorial":[{"visual":"1️⃣","title":"eins","text":"eins (one)"},{"visual":"2️⃣","title":"zwei","text":"zwei (two)"},{"visual":"3️⃣","title":"drei","text":"drei (three)"},{"visual":"4️⃣","title":"vier","text":"vier (four)"},{"visual":"5️⃣","title":"fünf","text":"fünf (five)"}],"exercises":[{"prompt":"1️⃣","expected":"eins"},{"prompt":"2️⃣","expected":"zwei"},{"prompt":"3️⃣","expected":"drei"},{"prompt":"4️⃣","expected":"vier"},{"prompt":"5️⃣","expected":"fünf"}],"type":"type_word","instructions":"Type the word."}', 16);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Basics: Colors', 'Intro for beginners', '{"tutorial":[{"visual":"🔴","title":"rot","text":"rot (red)"},{"visual":"🔵","title":"blau","text":"blau (blue)"},{"visual":"🟢","title":"grün","text":"grün (green)"},{"visual":"🟡","title":"gelb","text":"gelb (yellow)"}],"exercises":[{"prompt":"rot","options":["🔴","🍎","🐱","🚗"],"correct":0},{"prompt":"blau","options":["🔵","🍎","🐱","🚗"],"correct":0},{"prompt":"grün","options":["🟢","🍎","🐱","🚗"],"correct":0},{"prompt":"gelb","options":["🟡","🍎","🐱","🚗"],"correct":0},{"prompt":"rot","options":["🔴","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 17);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Basics: Colors', 'Intro for beginners', '{"tutorial":[{"visual":"🔴","title":"rot","text":"rot (red)"},{"visual":"🔵","title":"blau","text":"blau (blue)"},{"visual":"🟢","title":"grün","text":"grün (green)"},{"visual":"🟡","title":"gelb","text":"gelb (yellow)"}],"exercises":[{"prompt":"rot","expected":"rot"},{"prompt":"blau","expected":"blau"},{"prompt":"grün","expected":"grün"},{"prompt":"gelb","expected":"gelb"},{"prompt":"rot","expected":"rot"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 17);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Basics: Colors', 'Intro for beginners', '{"tutorial":[{"visual":"🔴","title":"rot","text":"rot (red)"},{"visual":"🔵","title":"blau","text":"blau (blue)"},{"visual":"🟢","title":"grün","text":"grün (green)"},{"visual":"🟡","title":"gelb","text":"gelb (yellow)"}],"exercises":[{"sentence":"🔴","question":"Pick the name","options":["rot","Apple","Car","Table"],"correct":0},{"sentence":"🔵","question":"Pick the name","options":["blau","Apple","Car","Table"],"correct":0},{"sentence":"🟢","question":"Pick the name","options":["grün","Apple","Car","Table"],"correct":0},{"sentence":"🟡","question":"Pick the name","options":["gelb","Apple","Car","Table"],"correct":0},{"sentence":"🔴","question":"Pick the name","options":["rot","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 17);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Basics: Colors', 'Intro for beginners', '{"tutorial":[{"visual":"🔴","title":"rot","text":"rot (red)"},{"visual":"🔵","title":"blau","text":"blau (blue)"},{"visual":"🟢","title":"grün","text":"grün (green)"},{"visual":"🟡","title":"gelb","text":"gelb (yellow)"}],"exercises":[{"prompt":"🔴","expected":"rot"},{"prompt":"🔵","expected":"blau"},{"prompt":"🟢","expected":"grün"},{"prompt":"🟡","expected":"gelb"},{"prompt":"🔴","expected":"rot"}],"type":"type_word","instructions":"Type the word."}', 17);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Basics: Family', 'Intro for beginners', '{"tutorial":[{"visual":"👩","title":"Mama","text":"Mama (Mom)"},{"visual":"👨","title":"Papa","text":"Papa (Dad)"},{"visual":"👶","title":"Baby","text":"Baby (Baby)"}],"exercises":[{"prompt":"Mama","options":["👩","🍎","🐱","🚗"],"correct":0},{"prompt":"Papa","options":["👨","🍎","🐱","🚗"],"correct":0},{"prompt":"Baby","options":["👶","🍎","🐱","🚗"],"correct":0},{"prompt":"Mama","options":["👩","🍎","🐱","🚗"],"correct":0},{"prompt":"Mama","options":["👩","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 18);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Basics: Family', 'Intro for beginners', '{"tutorial":[{"visual":"👩","title":"Mama","text":"Mama (Mom)"},{"visual":"👨","title":"Papa","text":"Papa (Dad)"},{"visual":"👶","title":"Baby","text":"Baby (Baby)"}],"exercises":[{"prompt":"Mama","expected":"mama"},{"prompt":"Papa","expected":"papa"},{"prompt":"Baby","expected":"baby"},{"prompt":"Mama","expected":"mama"},{"prompt":"Mama","expected":"mama"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 18);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Basics: Family', 'Intro for beginners', '{"tutorial":[{"visual":"👩","title":"Mama","text":"Mama (Mom)"},{"visual":"👨","title":"Papa","text":"Papa (Dad)"},{"visual":"👶","title":"Baby","text":"Baby (Baby)"}],"exercises":[{"sentence":"👩","question":"Pick the name","options":["Mama","Apple","Car","Table"],"correct":0},{"sentence":"👨","question":"Pick the name","options":["Papa","Apple","Car","Table"],"correct":0},{"sentence":"👶","question":"Pick the name","options":["Baby","Apple","Car","Table"],"correct":0},{"sentence":"👩","question":"Pick the name","options":["Mama","Apple","Car","Table"],"correct":0},{"sentence":"👩","question":"Pick the name","options":["Mama","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 18);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Basics: Family', 'Intro for beginners', '{"tutorial":[{"visual":"👩","title":"Mama","text":"Mama (Mom)"},{"visual":"👨","title":"Papa","text":"Papa (Dad)"},{"visual":"👶","title":"Baby","text":"Baby (Baby)"}],"exercises":[{"prompt":"👩","expected":"mama"},{"prompt":"👨","expected":"papa"},{"prompt":"👶","expected":"baby"},{"prompt":"👩","expected":"mama"},{"prompt":"👩","expected":"mama"}],"type":"type_word","instructions":"Type the word."}', 18);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Basics: Body', 'Intro for beginners', '{"tutorial":[{"visual":"👃","title":"Nase","text":"Nase (Nose)"},{"visual":"👂","title":"Ohr","text":"Ohr (Ear)"},{"visual":"👁️","title":"Auge","text":"Auge (Eye)"},{"visual":"👄","title":"Mund","text":"Mund (Mouth)"}],"exercises":[{"prompt":"Nase","options":["👃","🍎","🐱","🚗"],"correct":0},{"prompt":"Ohr","options":["👂","🍎","🐱","🚗"],"correct":0},{"prompt":"Auge","options":["👁️","🍎","🐱","🚗"],"correct":0},{"prompt":"Mund","options":["👄","🍎","🐱","🚗"],"correct":0},{"prompt":"Nase","options":["👃","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 19);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Basics: Body', 'Intro for beginners', '{"tutorial":[{"visual":"👃","title":"Nase","text":"Nase (Nose)"},{"visual":"👂","title":"Ohr","text":"Ohr (Ear)"},{"visual":"👁️","title":"Auge","text":"Auge (Eye)"},{"visual":"👄","title":"Mund","text":"Mund (Mouth)"}],"exercises":[{"prompt":"Nase","expected":"nase"},{"prompt":"Ohr","expected":"ohr"},{"prompt":"Auge","expected":"auge"},{"prompt":"Mund","expected":"mund"},{"prompt":"Nase","expected":"nase"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 19);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Basics: Body', 'Intro for beginners', '{"tutorial":[{"visual":"👃","title":"Nase","text":"Nase (Nose)"},{"visual":"👂","title":"Ohr","text":"Ohr (Ear)"},{"visual":"👁️","title":"Auge","text":"Auge (Eye)"},{"visual":"👄","title":"Mund","text":"Mund (Mouth)"}],"exercises":[{"sentence":"👃","question":"Pick the name","options":["Nase","Apple","Car","Table"],"correct":0},{"sentence":"👂","question":"Pick the name","options":["Ohr","Apple","Car","Table"],"correct":0},{"sentence":"👁️","question":"Pick the name","options":["Auge","Apple","Car","Table"],"correct":0},{"sentence":"👄","question":"Pick the name","options":["Mund","Apple","Car","Table"],"correct":0},{"sentence":"👃","question":"Pick the name","options":["Nase","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 19);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Basics: Body', 'Intro for beginners', '{"tutorial":[{"visual":"👃","title":"Nase","text":"Nase (Nose)"},{"visual":"👂","title":"Ohr","text":"Ohr (Ear)"},{"visual":"👁️","title":"Auge","text":"Auge (Eye)"},{"visual":"👄","title":"Mund","text":"Mund (Mouth)"}],"exercises":[{"prompt":"👃","expected":"nase"},{"prompt":"👂","expected":"ohr"},{"prompt":"👁️","expected":"auge"},{"prompt":"👄","expected":"mund"},{"prompt":"👃","expected":"nase"}],"type":"type_word","instructions":"Type the word."}', 19);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"B","options":["🐻","🍎","🐱","🚗"],"correct":0},{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0},{"prompt":"D","options":["🐉","🍎","🐱","🚗"],"correct":0},{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 20);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"Apfel","expected":"apfel"},{"prompt":"Bär","expected":"bär"},{"prompt":"Clown","expected":"clown"},{"prompt":"Drache","expected":"drache"},{"prompt":"Elefant","expected":"elefant"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 20);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0},{"sentence":"🐻","question":"Pick the name","options":["Bär","Apple","Car","Table"],"correct":0},{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0},{"sentence":"🐉","question":"Pick the name","options":["Drache","Apple","Car","Table"],"correct":0},{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 20);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"🍎","expected":"apfel"},{"prompt":"🐻","expected":"bär"},{"prompt":"🤡","expected":"clown"},{"prompt":"🐉","expected":"drache"},{"prompt":"🐘","expected":"elefant"}],"type":"type_word","instructions":"Type the word."}', 20);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"B","options":["🐻","🍎","🐱","🚗"],"correct":0},{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0},{"prompt":"D","options":["🐉","🍎","🐱","🚗"],"correct":0},{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 21);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"Apfel","expected":"apfel"},{"prompt":"Bär","expected":"bär"},{"prompt":"Clown","expected":"clown"},{"prompt":"Drache","expected":"drache"},{"prompt":"Elefant","expected":"elefant"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 21);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0},{"sentence":"🐻","question":"Pick the name","options":["Bär","Apple","Car","Table"],"correct":0},{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0},{"sentence":"🐉","question":"Pick the name","options":["Drache","Apple","Car","Table"],"correct":0},{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 21);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"🍎","expected":"apfel"},{"prompt":"🐻","expected":"bär"},{"prompt":"🤡","expected":"clown"},{"prompt":"🐉","expected":"drache"},{"prompt":"🐘","expected":"elefant"}],"type":"type_word","instructions":"Type the word."}', 21);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"B","options":["🐻","🍎","🐱","🚗"],"correct":0},{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0},{"prompt":"D","options":["🐉","🍎","🐱","🚗"],"correct":0},{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 22);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"Apfel","expected":"apfel"},{"prompt":"Bär","expected":"bär"},{"prompt":"Clown","expected":"clown"},{"prompt":"Drache","expected":"drache"},{"prompt":"Elefant","expected":"elefant"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 22);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0},{"sentence":"🐻","question":"Pick the name","options":["Bär","Apple","Car","Table"],"correct":0},{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0},{"sentence":"🐉","question":"Pick the name","options":["Drache","Apple","Car","Table"],"correct":0},{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 22);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"🍎","expected":"apfel"},{"prompt":"🐻","expected":"bär"},{"prompt":"🤡","expected":"clown"},{"prompt":"🐉","expected":"drache"},{"prompt":"🐘","expected":"elefant"}],"type":"type_word","instructions":"Type the word."}', 22);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"B","options":["🐻","🍎","🐱","🚗"],"correct":0},{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0},{"prompt":"D","options":["🐉","🍎","🐱","🚗"],"correct":0},{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 23);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"Apfel","expected":"apfel"},{"prompt":"Bär","expected":"bär"},{"prompt":"Clown","expected":"clown"},{"prompt":"Drache","expected":"drache"},{"prompt":"Elefant","expected":"elefant"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 23);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0},{"sentence":"🐻","question":"Pick the name","options":["Bär","Apple","Car","Table"],"correct":0},{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0},{"sentence":"🐉","question":"Pick the name","options":["Drache","Apple","Car","Table"],"correct":0},{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 23);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"🍎","expected":"apfel"},{"prompt":"🐻","expected":"bär"},{"prompt":"🤡","expected":"clown"},{"prompt":"🐉","expected":"drache"},{"prompt":"🐘","expected":"elefant"}],"type":"type_word","instructions":"Type the word."}', 23);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"B","options":["🐻","🍎","🐱","🚗"],"correct":0},{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0},{"prompt":"D","options":["🐉","🍎","🐱","🚗"],"correct":0},{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 24);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"Apfel","expected":"apfel"},{"prompt":"Bär","expected":"bär"},{"prompt":"Clown","expected":"clown"},{"prompt":"Drache","expected":"drache"},{"prompt":"Elefant","expected":"elefant"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 24);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0},{"sentence":"🐻","question":"Pick the name","options":["Bär","Apple","Car","Table"],"correct":0},{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0},{"sentence":"🐉","question":"Pick the name","options":["Drache","Apple","Car","Table"],"correct":0},{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 24);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"🍎","expected":"apfel"},{"prompt":"🐻","expected":"bär"},{"prompt":"🤡","expected":"clown"},{"prompt":"🐉","expected":"drache"},{"prompt":"🐘","expected":"elefant"}],"type":"type_word","instructions":"Type the word."}', 24);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'listening', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"A","options":["🍎","🍎","🐱","🚗"],"correct":0},{"prompt":"B","options":["🐻","🍎","🐱","🚗"],"correct":0},{"prompt":"C","options":["🤡","🍎","🐱","🚗"],"correct":0},{"prompt":"D","options":["🐉","🍎","🐱","🚗"],"correct":0},{"prompt":"E","options":["🐘","🍎","🐱","🚗"],"correct":0}],"type":"listen_and_choose","instructions":"Listen and pick the correct one."}', 25);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'speaking', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"Apfel","expected":"apfel"},{"prompt":"Bär","expected":"bär"},{"prompt":"Clown","expected":"clown"},{"prompt":"Drache","expected":"drache"},{"prompt":"Elefant","expected":"elefant"}],"type":"speak_and_compare","instructions":"Repeat the word."}', 25);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'reading', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"sentence":"🍎","question":"Pick the name","options":["Apfel","Apple","Car","Table"],"correct":0},{"sentence":"🐻","question":"Pick the name","options":["Bär","Apple","Car","Table"],"correct":0},{"sentence":"🤡","question":"Pick the name","options":["Clown","Apple","Car","Table"],"correct":0},{"sentence":"🐉","question":"Pick the name","options":["Drache","Apple","Car","Table"],"correct":0},{"sentence":"🐘","question":"Pick the name","options":["Elefant","Apple","Car","Table"],"correct":0}],"type":"read_and_choose","instructions":"What is this?"}', 25);

INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('de', 'A0', 'writing', 'Review', 'Intro for beginners', '{"tutorial":[{"visual":"🍎","title":"A","text":"Apfel (Apple). Sounds like: ah"},{"visual":"🐻","title":"B","text":"Bär (Bear). Sounds like: beh"},{"visual":"🤡","title":"C","text":"Clown (Clown). Sounds like: tseh"},{"visual":"🐉","title":"D","text":"Drache (Dragon). Sounds like: deh"},{"visual":"🐘","title":"E","text":"Elefant (Elephant). Sounds like: eh"}],"exercises":[{"prompt":"🍎","expected":"apfel"},{"prompt":"🐻","expected":"bär"},{"prompt":"🤡","expected":"clown"},{"prompt":"🐉","expected":"drache"},{"prompt":"🐘","expected":"elefant"}],"type":"type_word","instructions":"Type the word."}', 25);

