-- ============================================================
-- ENGLISH A1 PLUS LESSONS (20)
-- ============================================================

-- ─── ENGLISH LISTENING (A1+) ───────────────────────────────────
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A1', 'listening', 'Minimal Pairs', 'Distinguish between similar sounds.', '{"type":"listen_and_choose","instructions":"Listen and choose the word you hear.","exercises":[{"prompt":"ship","question":"Which word sounds like a boat?","options":["ship","sheep"],"correct":0,"hint":"Short ''i'' sound."},{"prompt":"sheep","question":"Which word is a farm animal?","options":["ship","sheep"],"correct":1,"hint":"Long ''ee'' sound."},{"prompt":"bat","question":"Which word is used in baseball?","options":["bat","bet"],"correct":0,"hint":"Short ''a'' sound."},{"prompt":"bet","question":"Which word means to gamble?","options":["bat","bet"],"correct":1,"hint":"Short ''e'' sound."},{"prompt":"fan","question":"Which word keeps you cool?","options":["fan","van"],"correct":0,"hint":"Starts with ''f''."}]}', 11),
('en', 'A1', 'listening', 'The Grocery Store', 'Listen to items being bought.', '{"type":"listen_and_choose","instructions":"Which item is being described?","exercises":[{"prompt":"A dozen red apples.","question":"How many apples?","options":["6","10","12"],"correct":2,"hint":"A dozen means twelve."},{"prompt":"A loaf of fresh bread.","question":"What is being bought?","options":["milk","bread","cheese"],"correct":1,"hint":"You slice this for sandwiches."},{"prompt":"A carton of orange juice.","question":"What container is mentioned?","options":["bottle","carton","bag"],"correct":1,"hint":"Starts with C."},{"prompt":"Two kilograms of sugar.","question":"What is the weight?","options":["1kg","2kg","3kg"],"correct":1,"hint":"Listen for the number."},{"prompt":"A bunch of yellow bananas.","question":"What color are the fruits?","options":["green","red","yellow"],"correct":2,"hint":"Common banana color."}]}', 12),
('en', 'A1', 'listening', 'Daily Routine Times', 'Listen to times for daily tasks.', '{"type":"listen_and_choose","instructions":"At what time does the action happen?","exercises":[{"prompt":"I wake up at half past six.","question":"Wake up time?","options":["6:00","6:30","7:00"],"correct":1,"hint":"Half past means :30."},{"prompt":"Breakfast is at quarter to eight.","question":"Breakfast time?","options":["7:15","7:45","8:15"],"correct":1,"hint":"Quarter to means :45."},{"prompt":"I go to work at eight fifteen.","question":"Work time?","options":["8:15","8:50","9:15"],"correct":0,"hint":"Eight plus fifteen."},{"prompt":"Lunch is at exactly noon.","question":"Lunch time?","options":["11:00","12:00","13:00"],"correct":1,"hint":"Noon is midday."},{"prompt":"I get home at five o''clock.","question":"Home time?","options":["16:00","17:00","18:00"],"correct":1,"hint":"5:00."}]}', 13),
('en', 'A1', 'listening', 'Complex Directions', 'Listen to 2-step directions.', '{"type":"listen_and_choose","instructions":"What is the first step?","exercises":[{"prompt":"Go straight and then turn left.","question":"First action?","options":["Turn left","Go straight","Stop"],"correct":1,"hint":"Go straight comes first."},{"prompt":"Turn right at the bank and stop.","question":"Where to turn?","options":["At the park","At the bank","At the station"],"correct":1,"hint":"Listen for the building."},{"prompt":"Walk two blocks and look for the red door.","question":"Keep walking for how long?","options":["1 block","2 blocks","3 blocks"],"correct":1,"hint":"Listen for the number."},{"prompt":"Take the bus and get off at the third stop.","question":"Which stop?","options":["1st","2nd","3rd"],"correct":2,"hint":"Ordinal number."},{"prompt":"Cross the street and wait by the tree.","question":"Where to wait?","options":["By the tree","In the shop","At the bus stop"],"correct":0,"hint":"Outdoor nature object."}]}', 14),
('en', 'A1', 'listening', 'Ordering Drinks', 'Listen to coffee shop orders.', '{"type":"listen_and_choose","instructions":"What did the customer order?","exercises":[{"prompt":"A large latte with sugar.","question":"Size of the drink?","options":["small","medium","large"],"correct":2,"hint":"Biggest size."},{"prompt":"A small espresso, no milk.","question":"Is there milk?","options":["yes","no"],"correct":1,"hint":"No milk mentioned."},{"prompt":"Two medium teas with lemon.","question":"How many drinks?","options":["1","2","3"],"correct":1,"hint":"Listen for quantity."},{"prompt":"An iced coffee with cream.","question":"Temperature?","options":["hot","iced"],"correct":1,"hint":"Cold drink."},{"prompt":"A hot chocolate with marshmallows.","question":"What is the topping?","options":["cream","chocolate","marshmallows"],"correct":2,"hint":"White fluffy sweets."}]}', 15);

-- ─── ENGLISH SPEAKING (A1+) ───────────────────────────────────
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A1', 'speaking', 'Polite Introductions', 'Practice polite ways to meet people.', '{"type":"speak_and_repeat","instructions":"Repeat the polite phrase clearly.","exercises":[{"prompt":"Hello, it is a pleasure to meet you.","expected":"Hello it is a pleasure to meet you","hint":"Formal introduction."},{"prompt":"Could you tell me your name, please?","expected":"Could you tell me your name please","hint":"Polite question."},{"prompt":"I would like to introduce my friend, Sarah.","expected":"I would like to introduce my friend Sarah","hint":"Introducing others."},{"prompt":"Nice to see you again after a long time.","expected":"Nice to see you again after a long time","hint":"Greeting an old friend."},{"prompt":"May I have your phone number?","expected":"May I have your phone number","hint":"Asking for contact info."}]}', 11),
('en', 'A1', 'speaking', 'At the Doctor''s', 'Practice basic medical symptoms.', '{"type":"speak_and_repeat","instructions":"State your symptom clearly.","exercises":[{"prompt":"I have a very bad headache today.","expected":"I have a very bad headache today","hint":"Pain in the head."},{"prompt":"My stomach hurts after eating lunch.","expected":"My stomach hurts after eating lunch","hint":"Digestive pain."},{"prompt":"I feel a bit dizzy and tired.","expected":"I feel a bit dizzy and tired","hint":"Not feeling steady."},{"prompt":"I have a sore throat and a cough.","expected":"I have a sore throat and a cough","hint":"Cold symptoms."},{"prompt":"Could I see the doctor this afternoon?","expected":"Could I see the doctor this afternoon","hint":"Requesting appointment."}]}', 12),
('en', 'A1', 'speaking', 'Giving Opinions', 'Express simple likes and dislikes.', '{"type":"speak_and_repeat","instructions":"Express your opinion clearly.","exercises":[{"prompt":"I really love eating Italian pizza.","expected":"I really love eating Italian pizza","hint":"Strong like."},{"prompt":"I don''t like watching scary movies.","expected":"I dont like watching scary movies","hint":"Dislike."},{"prompt":"Football is my favorite sport to play.","expected":"Football is my favorite sport to play","hint":"Preference."},{"prompt":"I think this book is very interesting.","expected":"I think this book is very interesting","hint":"Giving a thought."},{"prompt":"Traveling to new cities is exciting.","expected":"Traveling to new cities is exciting","hint":"Opinion on travel."}]}', 13),
('en', 'A1', 'speaking', 'Time Management', 'Talking about schedules.', '{"type":"speak_and_repeat","instructions":"State your schedule item.","exercises":[{"prompt":"I have a meeting at ten o''clock.","expected":"I have a meeting at ten oclock","hint":"Schedule time."},{"prompt":"My train leaves in twenty minutes.","expected":"My train leaves in twenty minutes","hint":"Transport timing."},{"prompt":"I am usually busy on Monday mornings.","expected":"I am usually busy on Monday mornings","hint":"General schedule."},{"prompt":"The supermarket closes at midnight.","expected":"The supermarket closes at midnight","hint":"Closing time."},{"prompt":"Let''s meet for lunch at half past one.","expected":"Lets meet for lunch at half past one","hint":"Proposal."}]}', 14),
('en', 'A1', 'speaking', 'Emergency Phrases', 'Basic calls for help.', '{"type":"speak_and_repeat","instructions":"Repeat the emergency call.","exercises":[{"prompt":"Help! I lost my wallet in the park.","expected":"Help I lost my wallet in the park","hint":"Asking for help."},{"prompt":"Where is the nearest police station?","expected":"Where is the nearest police station","hint":"Location query."},{"prompt":"I need to call an ambulance quickly.","expected":"I need to call an ambulance quickly","hint":"Urgent request."},{"prompt":"Is there a pharmacy open nearby?","expected":"Is there a pharmacy open nearby","hint":"Medicine search."},{"prompt":"I am lost, can you help me?","expected":"I am lost can you help me","hint":"Personal status."}]}', 15);

-- ─── ENGLISH READING (A1+) ───────────────────────────────────
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A1', 'reading', 'Modern Family', 'Read about a family with multiple pets.', '{"type":"read_and_choose","instructions":"Read the description and answer.","exercises":[{"sentence":"My brother has a large dog and two small cats. My sister has a bird.","question":"Who has the bird?","options":["The brother","The sister","The narrator"],"correct":1,"explanation":"The sister has a bird."},{"sentence":"The dog is brown, but the cats are white and black.","question":"What color is the dog?","options":["white","black","brown"],"correct":2,"explanation":"The dog is brown."},{"sentence":"We all live in a big house with a blue door.","question":"What color is the door?","options":["blue","green","red"],"correct":0,"explanation":"The door is blue."},{"sentence":"On Sundays, we walk in the park near the river.","question":"When do they walk?","options":["Fridays","Saturdays","Sundays"],"correct":2,"explanation":"Sundays."},{"sentence":"My parents love gardening and planting flowers.","question":"What do the parents do?","options":["Running","Gardening","Fishing"],"correct":1,"explanation":"They love gardening."}]}', 11),
('en', 'A1', 'reading', 'The Menu', 'Read a cafe menu and choose items.', '{"type":"read_and_choose","instructions":"Find the item on the menu.","exercises":[{"sentence":"Breakfast Special: Eggs and Toast - $5. Coffee/Tea - $2.","question":"How much is tea?","options":["$2","$5","$7"],"correct":0,"explanation":"Coffee/Tea is $2."},{"sentence":"Lunch: Chicken Sandwich ($6) or Tomato Soup ($4).","question":"Which is cheaper for lunch?","options":["Sandwich","Soup"],"correct":1,"explanation":"Soup is $4, sandwich is $6."},{"sentence":"Kids Meal: Pasta and Juice - $3. Free cookie with every meal!","question":"What comes free?","options":["Pasta","Juice","Cookie"],"correct":2,"explanation":"Free cookie with every meal."},{"sentence":"We are open from 8am to 8pm every day.","question":"Are they open at 7pm?","options":["Yes","No"],"correct":0,"explanation":"They are open until 8pm."},{"sentence":"Located at North Street, opposite the library.","question":"What is across the street?","options":["A bank","A library","A park"],"correct":1,"explanation":"Opposite the library."}]}', 12),
('en', 'A1', 'reading', 'My Hobby: Photography', 'Read about taking photos.', '{"type":"read_and_choose","instructions":"Read and understand the hobby.","exercises":[{"sentence":"I take my camera everywhere I go. I love taking photos of nature.","question":"What does the person photograph?","options":["Buildings","Nature","People"],"correct":1,"explanation":"They love taking photos of nature."},{"sentence":"Sunset is the best time for beautiful pictures.","question":"When is the best time?","options":["Morning","Noon","Sunset"],"correct":2,"explanation":"Sunset is the best time."},{"sentence":"I have a digital camera, not an old film camera.","question":"What type of camera is it?","options":["Digital","Film"],"correct":0,"explanation":"It is a digital camera."},{"sentence":"Next month, I will have an exhibition at the local gallery.","question":"Where is the exhibition?","options":["Museum","Gallery","School"],"correct":1,"explanation":"At the local gallery."},{"sentence":"My friend Mark is a professional photographer too.","question":"Is Mark a photographer?","options":["Yes","No"],"correct":0,"explanation":"Mark is a professional photographer."}]}', 13),
('en', 'A1', 'reading', 'Email to a Friend', 'A short email from a vacation.', '{"type":"read_and_choose","instructions":"Understand the email content.","exercises":[{"sentence":"Hi Tom, I am in Spain right now! The weather is very hot and sunny.","question":"Where is the sender?","options":["Italy","Spain","France"],"correct":1,"explanation":"I am in Spain."},{"sentence":"Yesterday, I visited a famous museum in the center of the city.","question":"What did they visit?","options":["A park","A museum","A beach"],"correct":1,"explanation":"Visited a museum."},{"sentence":"I am eating a lot of seafood and drinking cold orange juice.","question":"What are they eating?","options":["Steak","Seafood","Pasta"],"correct":1,"explanation":"Eating a lot of seafood."},{"sentence":"I am coming home next Saturday on the evening flight.","question":"When are they coming home?","options":["Friday","Saturday","Sunday"],"correct":1,"explanation":"Next Saturday."},{"sentence":"See you soon, Anna.","question":"Who wrote the email?","options":["Tom","Anna","Mark"],"correct":1,"explanation":"Anna wrote it."}]}', 14),
('en', 'A1', 'reading', 'Job Advertisement', 'Basic job requirements.', '{"type":"read_and_choose","instructions":"Find info in the ad.","exercises":[{"sentence":"Wanted: Part-time waiter for a busy Italian restaurant.","question":"What is the job?","options":["Cook","Waiter","Manager"],"correct":1,"explanation":"Wanted: Part-time waiter."},{"sentence":"Hours: 6pm to 11pm, Thursday to Sunday.","question":"Do you work on Mondays?","options":["Yes","No"],"correct":1,"explanation":"Thursday to Sunday."},{"sentence":"Experience: Not required, but helpful. We provide training.","question":"Do you need experience?","options":["Yes","No"],"correct":1,"explanation":"Not required."},{"sentence":"Pay: $12 per hour plus tips.","question":"What is the hourly rate?","options":["$10","$12","$15"],"correct":1,"explanation":"$12 per hour."},{"sentence":"Call 555-0199 to apply. Ask for Maria.","question":"Who should you ask for?","options":["John","Maria","Sarah"],"correct":1,"explanation":"Ask for Maria."}]}', 15);

-- ─── ENGLISH WRITING (A1+) ───────────────────────────────────
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A1', 'writing', 'Pronoun Power', 'Build sentences with correct pronouns.', '{"type":"type_word","instructions":"Type the correct pronoun.","exercises":[{"prompt":"My brother is tall. [He/She] is a basketball player.","expected":"He","hint":"Brother is male."},{"prompt":"My sister and I are students. [We/They] go to school.","expected":"We","hint":"Includes the narrator."},{"prompt":"Look at those birds! [It/They] are flying south.","expected":"They","hint":"Plural animals."},{"prompt":"The cat is sleeping. [It/He] is very cute.","expected":"It","hint":"Neutral animal pronoun."},{"prompt":"John and Mary are married. [We/They] live in London.","expected":"They","hint":"Third person plural."}]}', 11),
('en', 'A1', 'writing', 'Plural Fun', 'Change words from singular to plural.', '{"type":"type_word","instructions":"Type the plural form.","exercises":[{"prompt":"One dog, two...","expected":"dogs","hint":"Just add -s."},{"prompt":"One city, two...","expected":"cities","hint":"-y becomes -ies."},{"prompt":"One child, two...","expected":"children","hint":"Irregular plural."},{"prompt":"One man, two...","expected":"men","hint":"Vowel change."},{"prompt":"One apple, two...","expected":"apples","hint":"Add -s."}]}', 12),
('en', 'A1', 'writing', 'Daily Objects', 'Type names of common things.', '{"type":"type_word","instructions":"Type the object name.","exercises":[{"prompt":"You use this to open a door.","expected":"key","hint":"Small metal object."},{"prompt":"You use this to call people.","expected":"phone","hint":"Electronic device."},{"prompt":"You use this to umbrella.","expected":"umbrella","hint":"Protects from rain."},{"prompt":"You wear this on your wrist to see time.","expected":"watch","hint":"Small clock."},{"prompt":"You sit on this.","expected":"chair","hint":"Furniture."}]}', 13),
('en', 'A1', 'writing', 'Adjective Order', 'Describe things properly.', '{"type":"type_word","instructions":"Arrange: color + noun.","exercises":[{"prompt":"A [red / car]","expected":"red car","hint":"Adjective first."},{"prompt":"A [big / house]","expected":"big house","hint":"Size first."},{"prompt":"A [blue / sky]","expected":"blue sky","hint":"Color first."},{"prompt":"A [tall / man]","expected":"tall man","hint":"Height adjective."},{"prompt":"A [sweet / apple]","expected":"sweet apple","hint":"Taste adjective."}]}', 14),
('en', 'A1', 'writing', 'Simple Actions', 'Type verbs for basic actions.', '{"type":"type_word","instructions":"Type the action.","exercises":[{"prompt":"You use your eyes to...","expected":"see","hint":"Visual sense."},{"prompt":"You use your ears to...","expected":"hear","hint":"Auditory sense."},{"prompt":"You use your legs to...","expected":"walk","hint":"Basic movement."},{"prompt":"You use your mouth to...","expected":"eat","hint":"Taking food."},{"prompt":"You use a pen to...","expected":"write","hint":"Creating text."}]}', 15);
