-- German Course Seed Data
-- 40 Lessons: 4 Skills (LSRW) x 2 Levels (A1, A2) x 5 Lessons each
-- All lessons have 5 high-quality exercises

USE lingospark;

-- Ensure German is enabled
UPDATE languages SET enabled = TRUE, name = 'German', course_title = 'Speak German' WHERE code = 'de';
INSERT IGNORE INTO languages (code, name, course_title, enabled) VALUES ('de', 'German', 'Speak German', TRUE);
UPDATE languages SET course_title = 'Speak English' WHERE code = 'en';

-- ============================================================
-- A1 GERMAN LISTENING
-- ============================================================
INSERT INTO lessons (language_code, cefr_level, skill, title, title_translation, description, description_translation, content, order_index) VALUES
('de', 'A1', 'listening', 'Begrüßungen', 'Greetings', 'Lerne grundlegende Begrüßungen auf Deutsch', 'Learn basic greetings in German',
'{"type":"listen_and_choose","instructions":"Höre dir die Begrüßung an und wähle das richtige Bild.","exercises":[{"prompt":"Hallo! Wie geht es dir?","options":["Eine winkende Person","Eine schlafende Person","Jemand beim Essen","Jemand beim Laufen"],"correct":0,"hint":"Das ist eine freundliche Begrüßung","hint_translation":"This is a friendly greeting"},{"prompt":"Auf Wiedersehen! Bis später!","options":["Jemand kommt an","Eine winkende Person (beim Abschied)","Jemand sitzt","Jemand kocht"],"correct":1,"hint":"Jemand geht weg","hint_translation":"Someone is going away"},{"prompt":"Guten Morgen!","options":["Nachthimmel","Sonnenaufgang","Regentag","Sonnenuntergang"],"correct":1,"hint":"Denke daran, wenn du aufwachst","hint_translation":"Think of this when you wake up"},{"prompt":"Gute Nacht! Schlaf gut!","options":["Sonniger Day","Person bei der Arbeit","Mond und Sterne","Spielplatz"],"correct":2,"hint":"Zeit zum Schlafen","hint_translation":"Time to sleep"},{"prompt":"Freut mich, Sie kennenzulernen!","options":["Zwei Personen schütteln Hände","Eine Person allein","Eine wütende Person","Jemand läuft"],"correct":0,"hint":"Jemanden neu treffen","hint_translation":"Meeting someone new"}]}', 1),

('de', 'A1', 'listening', 'Zahlen 1 bis 10', 'Numbers 1 to 10', 'Höre und lerne die Zahlen von eins bis zehn', 'Listen and learn the numbers from one to ten',
'{"type":"listen_and_choose","instructions":"Höre die Zahl und wähle die richtige Ziffer.","exercises":[{"prompt":"Drei","options":["1","3","5","7"],"correct":1,"hint":"Kommt nach zwei","hint_translation":"Comes after two"},{"prompt":"Sieben","options":["4","6","7","9"],"correct":2,"hint":"Kommt nach sechs","hint_translation":"Comes after six"},{"prompt":"Eins","options":["1","2","10","8"],"correct":0,"hint":"Die allererste Zahl","hint_translation":"The very first number"},{"prompt":"Zehn","options":["2","5","8","10"],"correct":3,"hint":"Zwei Hände voll Finger","hint_translation":"Two hands full of fingers"},{"prompt":"Fünf","options":["3","5","4","6"],"correct":1,"hint":"Genau in der Mitte","hint_translation":"Right in the middle"}]}', 2),

('de', 'A1', 'listening', 'Farben um uns herum', 'Colors Around Us', 'Höre und identifiziere Farben', 'Listen and identify colors',
'{"type":"listen_and_choose","instructions":"Höre den Farbnamen und wähle die richtige Farbe.","exercises":[{"prompt":"Rot","options":["🔴","🔵","🟢","🟡"],"correct":0,"hint":"Die Farbe der Feuerwehr","hint_translation":"The color of the fire truck"},{"prompt":"Blau","options":["🟠","🔵","🟣","🔴"],"correct":1,"hint":"Die Farbe des Himmels","hint_translation":"The color of the sky"},{"prompt":"Grün","options":["🟡","🔴","🟢","🔵"],"correct":2,"hint":"Die Farbe von Gras","hint_translation":"The color of grass"},{"prompt":"Gelb","options":["🟢","🟣","🔴","🟡"],"correct":3,"hint":"Die Farbe der Sonne","hint_translation":"The color of the sun"},{"prompt":"Orange","options":["🟠","🔵","🟢","🟡"],"correct":0,"hint":"Eine Frucht hat diesen Namen auch","hint_translation":"A fruit has this name too"}]}', 3),

('de', 'A1', 'listening', 'Meine Familie', 'My Family', 'Höre und lerne die Namen der Familienmitglieder', 'Listen and learn the names of family members',
'{"type":"listen_and_choose","instructions":"Höre zu und wähle die beschriebene Person.","exercises":[{"prompt":"Das ist meine Mutter. Sie ist sehr nett.","options":["👩 Mutter","👨 Vater","👦 Bruder","👧 Schwester"],"correct":0,"hint":"Ein weiblicher Elternteil","hint_translation":"A female parent"},{"prompt":"Mein Vater kocht gerne.","options":["👧 Schwester","👦 Bruder","👨 Vater","👩 Mutter"],"correct":2,"hint":"Ein männlicher Elternteil","hint_translation":"A male parent"},{"prompt":"Ich habe eine kleine Schwester.","options":["👦 Bruder","👨 Vater","👩 Mutter","👧 Schwester"],"correct":3,"hint":"Ein junges weibliches Geschwisterkind","hint_translation":"A young female sibling"},{"prompt":"Mein Bruder spielt Fußball.","options":["👦 Bruder","👧 Schwester","👩 Mutter","👨 Vater"],"correct":0,"hint":"Ein männliches Geschwisterkind","hint_translation":"A male sibling"},{"prompt":"Oma erzählt uns Geschichten.","options":["👨 Vater","👩 Mutter","👵 Oma","👦 Bruder"],"correct":2,"hint":"Die Mutter deiner Eltern","hint_translation":"The mother of your parents"}]}', 4),

('de', 'A1', 'listening', 'Tiere, die ich kenne', 'Animals I Know', 'Höre Tiernamen und Geräusche', 'Listen to animal names and sounds',
'{"type":"listen_and_choose","instructions":"Höre zu und wähle das richtige Tier.","exercises":[{"prompt":"Die Katze sagt miau.","options":["🐱","🐶","🐦","🐸"],"correct":0,"hint":"Ein kleines Haustier mit weichem Fell","hint_translation":"A small pet with soft fur"},{"prompt":"Der Hund bellt.","options":["🐱","🐶","🐟","🐘"],"correct":1,"hint":"Ein treues Haustier, das Stöckchen holt","hint_translation":"A faithful pet that fetches sticks"},{"prompt":"Schau mal, der große Elefant!","options":["🐁","🐦","🐘","🐟"],"correct":2,"hint":"Das größte Landsäugetier","hint_translation":"The largest land mammal"},{"prompt":"Der Vogel singt.","options":["🐸","🐦","🐱","🐶"],"correct":1,"hint":"Er hat Flügel und Federn","hint_translation":"It has wings and feathers"},{"prompt":"Der Fisch schwimmt im Wasser.","options":["🐦","🐱","🐶","🐟"],"correct":3,"hint":"Er lebt unter Wasser","hint_translation":"It lives under water"}]}', 5);

-- ============================================================
-- A1 GERMAN SPEAKING
-- ============================================================
INSERT INTO lessons (language_code, cefr_level, skill, title, title_translation, description, description_translation, content, order_index) VALUES
('de', 'A1', 'speaking', 'Sag Hallo', 'Say Hello', 'Übe, Leute zu begrüßen', 'Practice greeting people',
'{"type":"speak_and_compare","instructions":"Höre dir den Satz an und sprich ihn laut aus.","exercises":[{"prompt":"Hallo!","expected":"hallo","hint":"Eine einfache Begrüßung","hint_translation":"A simple greeting"},{"prompt":"Guten Morgen!","expected":"guten morgen","hint":"Was man am Morgen sagt","hint_translation":"What you say in the morning"},{"prompt":"Wie geht es dir?","expected":"wie geht es dir","hint":"Fragen, wie sich jemand fühlt","hint_translation":"Asking how someone feels"},{"prompt":"Freut mich!","expected":"freut mich","hint":"Wenn man jemanden neu trifft","hint_translation":"When meeting someone new"},{"prompt":"Tschüss!","expected":"tschüss","hint":"Wenn man geht","hint_translation":"When you leave"}]}', 1),

('de', 'A1', 'speaking', 'Über mich', 'About Me', 'Übe, dich vorzustellen', 'Practice introducing yourself',
'{"type":"speak_and_compare","instructions":"Sprich jeden Satz laut aus.","exercises":[{"prompt":"Ich heiße...","expected":"ich heiße","hint":"Nenne deinen Namen","hint_translation":"Say your name"},{"prompt":"Ich bin sechs Jahre alt.","expected":"ich bin sechs jahre alt","hint":"Nenne dein Alter","hint_translation":"Say your age"},{"prompt":"Ich spiele gerne.","expected":"ich spiele gerne","hint":"Etwas, das dir Spaß macht","hint_translation":"Something that is fun for you"},{"prompt":"Ich bin glücklich!","expected":"ich bin glücklich","hint":"Wie du dich fühlst","hint_translation":"How you feel"},{"prompt":"Danke schön!","expected":"danke schön","hint":"Sei höflich","hint_translation":"Be polite"}]}', 2),

('de', 'A1', 'speaking', 'Zähl mit mir', 'Count With Me', 'Übe, Zahlen laut auszusprechen', 'Practice saying numbers out loud',
'{"type":"speak_and_compare","instructions":"Sprich jede Zahl deutlich aus.","exercises":[{"prompt":"Eins","expected":"eins","hint":"Die erste Zahl","hint_translation":"The first number"},{"prompt":"Zwei","expected":"zwei","hint":"Nach eins","hint_translation":"After one"},{"prompt":"Fünf","expected":"fünf","hint":"Die Hälfte von zehn","hint_translation":"Half of ten"},{"prompt":"Acht","expected":"acht","hint":"Nach sieben","hint_translation":"After seven"},{"prompt":"Zehn","expected":"zehn","hint":"Alle Finger","hint_translation":"All fingers"}]}', 3),

('de', 'A1', 'speaking', 'Nenne die Farben', 'Name the Colors', 'Farbnamen laut sagen', 'Say color names out loud',
'{"type":"speak_and_compare","instructions":"Schau dir die Farbe an und sag ihren Namen.","exercises":[{"prompt":"Rot 🔴","expected":"rot","hint":"Farbe des Feuers","hint_translation":"Color of fire"},{"prompt":"Blau 🔵","expected":"blau","hint":"Farbe des Meeres","hint_translation":"Color of the sea"},{"prompt":"Grün 🟢","expected":"grün","hint":"Farbe der Blätter","hint_translation":"Color of leaves"},{"prompt":"Gelb 🟡","expected":"gelb","hint":"Farbe der Bananen","hint_translation":"Color of bananas"},{"prompt":"Lila 🟣","expected":"lila","hint":"Mischung aus Rot und Blau","hint_translation":"Mix of red and blue"}]}', 4),

('de', 'A1', 'speaking', 'Tiernamen', 'Animal Names', 'Sag die Namen der Tiere laut', 'Say the names of animals out loud',
'{"type":"speak_and_compare","instructions":"Sag den Tiernamen, wenn du das Bild siehst!","exercises":[{"prompt":"🐱 Welches Tier ist das?","expected":"katze","hint":"Es sagt miau","hint_translation":"It says meow"},{"prompt":"🐶 Welches Tier ist das?","expected":"hund","hint":"Es sagt wuff","hint_translation":"It says woof"},{"prompt":"🐦 Welches Tier ist das?","expected":"vogel","hint":"Es kann fliegen","hint_translation":"It can fly"},{"prompt":"🐟 Welches Tier ist das?","expected":"fisch","hint":"Es schwimmt","hint_translation":"It swims"},{"prompt":"🐘 Welches Tier ist das?","expected":"elefant","hint":"Sehr groß mit Rüssel","hint_translation":"Very large with a trunk"}]}', 5);

-- ============================================================
-- A1 GERMAN READING
-- ============================================================
INSERT INTO lessons (language_code, cefr_level, skill, title, title_translation, description, description_translation, content, order_index) VALUES
('de', 'A1', 'reading', 'Wort-Zuordnung', 'Word Matching', 'Einfache Wörter lesen und Bildern zuordnen', 'Read simple words and match with pictures',
'{"type":"read_and_match","instructions":"Lies das Wort und wähle das passende Bild.","exercises":[{"word":"Katze","options":["🐱","🐶","🐟","🐦"],"correct":0},{"word":"Sonne","options":["🌙","⭐","☀️","🌧️"],"correct":2},{"word":"Buch","options":["📱","📖","🎮","🎸"],"correct":1},{"word":"Apfel","options":["🍌","🍇","🍎","🍊"],"correct":2},{"word":"Haus","options":["🏫","🏠","🏥","🏪"],"correct":1}]}', 1),

('de', 'A1', 'reading', 'Einfache Sätze', 'Simple Sentences', 'Kurze Sätze lesen und verstehen', 'Read and understand short sentences',
'{"type":"read_and_choose","instructions":"Lies den Satz und wähle die Bedeutung.","exercises":[{"sentence":"Die Katze ist auf der Matte.","question":"Wo ist die Katze?","options":["Auf der Matte","Unter dem Tisch","In der Kiste","Auf dem Bett"],"correct":0},{"sentence":"Ich habe zwei Äpfel.","question":"Wie viele Äpfel?","options":["Eins","Zwei","Drei","Vier"],"correct":1},{"sentence":"Die Sonne ist gelb.","question":"Welche Farbe hat die Sonne?","options":["Rot","Blau","Gelb","Grün"],"correct":2},{"sentence":"Mein Hund ist groß.","question":"Was ist groß?","options":["Die Katze","Der Vogel","Der Fisch","Der Hund"],"correct":3},{"sentence":"Sie mag Eiscreme.","question":"Was mag sie?","options":["Eiscreme","Pizza","Kuchen","Brot"],"correct":0}]}', 2),

('de', 'A1', 'reading', 'Lückentext', 'Fill in the Blanks', 'Vervollständige einfache Sätze', 'Complete simple sentences',
'{"type":"fill_blank","instructions":"Lies den Satz und wähle das fehlende Wort.","exercises":[{"sentence":"Der Himmel ist ___.","options":["blau","groß","schnell","heiß"],"correct":0},{"sentence":"Ich ___ ein Schüler.","options":["ist","bin","sind","sein"],"correct":1},{"sentence":"Sie ___ zur Schule.","options":["gehe","geht","gehen","gegangen"],"correct":1},{"sentence":"Wir haben ___ Hunde.","options":["ein","eine","zwei","der"],"correct":2},{"sentence":"Das ist ___ Apfel.","options":["ein","eine","der","zwei"],"correct":0}]}', 3),

('de', 'A1', 'reading', 'Richtig oder Falsch', 'True or False', 'Lies und entscheide, ob die Aussagen stimmen', 'Read and decide if the statements are correct',
'{"type":"true_false","instructions":"Lies den Satz. Richtig oder Falsch?","exercises":[{"statement":"Eine Katze kann fliegen.","correct":false,"explanation":"Katzen können nicht fliegen. Vögel können fliegen!"},{"statement":"Die Sonne ist heiß.","correct":true,"explanation":"Ja! Die Sonne ist sehr heiß."},{"statement":"Fische leben im Wasser.","correct":true,"explanation":"Richtig! Fische leben im Wasser."},{"statement":"Eiscreme ist heiß.","correct":false,"explanation":"Nein! Eiscreme ist kalt und lecker."},{"statement":"Menschen haben zwei Augen.","correct":true,"explanation":"Ja! Wir haben zwei Augen."}]}', 4),

('de', 'A1', 'reading', 'Wortgruppen', 'Word Groups', 'Verwandte Wörter zusammenfügen', 'Assemble related words',
'{"type":"read_and_match","instructions":"Lies das Wort und wähle die passende Gruppe.","exercises":[{"word":"Hund","options":["Tiere","Essen","Farben","Zahlen"],"correct":0},{"word":"Rot","options":["Tiere","Essen","Farben","Zahlen"],"correct":2},{"word":"Apfel","options":["Tiere","Essen","Farben","Zahlen"],"correct":1},{"word":"Drei","options":["Tiere","Essen","Farben","Zahlen"],"correct":3},{"word":"Banane","options":["Tiere","Essen","Farben","Zahlen"],"correct":1}]}', 5);

-- ============================================================
-- A1 GERMAN WRITING
-- ============================================================
INSERT INTO lessons (language_code, cefr_level, skill, title, title_translation, description, description_translation, content, order_index) VALUES
('de', 'A1', 'writing', 'Buchstaben tippen', 'Typing Letters', 'Einzelne Buchstaben tippen üben', 'Practice typing individual letters',
'{"type":"type_word","instructions":"Tippe den Buchstaben, den du siehst.","exercises":[{"prompt":"Tippe: A","expected":"A","hint":"Der erste Buchstabe","hint_translation":"The first letter"},{"prompt":"Tippe: B","expected":"B","hint":"Der zweite Buchstabe","hint_translation":"The second letter"},{"prompt":"Tippe: C","expected":"C","hint":"Das Wort Clown beginnt damit","hint_translation":"The word Clown starts with this"},{"prompt":"Tippe: D","expected":"D","hint":"Das Wort Dino beginnt damit","hint_translation":"The word Dino starts with this"},{"prompt":"Tippe: E","expected":"E","hint":"Das Wort Elefant beginnt damit","hint_translation":"The word Elephant starts with this"}]}', 1),

('de', 'A1', 'writing', 'Wörter buchstabieren', 'Spelling Words', 'Kurze Wörter richtig schreiben', 'Write short words correctly',
'{"type":"type_word","instructions":"Höre das Wort und tippe es richtig.","exercises":[{"prompt":"katze","expected":"katze","hint":"🐱 Fünf Buchstaben, beginnt mit K","hint_translation":"Five letters, starts with K"},{"prompt":"hund","expected":"hund","hint":"🐶 Vier Buchstaben, beginnt mit H","hint_translation":"Four letters, starts with H"},{"prompt":"sonne","expected":"sonne","hint":"☀️ Fünf Buchstaben, beginnt mit S","hint_translation":"Five letters, starts with S"},{"prompt":"rot","expected":"rot","hint":"🔴 Drei Buchstaben, eine Farbe","hint_translation":"Three letters, a color"},{"prompt":"groß","expected":"groß","hint":"Das Gegenteil von klein","hint_translation":"The opposite of small"}]}', 2),

('de', 'A1', 'writing', 'Worträtsel', 'Word Puzzles', 'Buchstaben ordnen, um Wörter zu bilden', 'Arrange letters to form words',
'{"type":"unscramble","instructions":"Die Buchstaben sind vertauscht! Tippe das richtige Wort.","exercises":[{"scrambled":"atkez","expected":"katze","hint":"🐱 Ein Haustier, das miau sagt","hint_translation":"A pet that says meow"},{"scrambled":"neons","expected":"sonne","hint":"☀️ Sie scheint am Himmel","hint_translation":"It shines in the sky"},{"scrambled":"faple","expected":"apfel","hint":"🍎 Eine rote Frucht","hint_translation":"A red fruit"},{"scrambled":"hchu","expected":"buch","hint":"📖 Man kann es lesen","hint_translation":"You can read it"},{"scrambled":"chisf","expected":"fisch","hint":"🐟 Er schwimmt im Wasser","hint_translation":"It swims in water"}]}', 3),

('de', 'A1', 'writing', 'Wort vervollständigen', 'Completing Words', 'Fehlende Buchstaben einfüllen', 'Fill in missing letters',
'{"type":"fill_letters","instructions":"Einige Buchstaben fehlen. Tippe das ganze Wort.","exercises":[{"partial":"k_tze","expected":"katze","hint":"🐱 Ein flauschiges Tier","hint_translation":"A fluffy animal"},{"partial":"h_nd","expected":"hund","hint":"🐶 Ein treues Tier","hint_translation":"A faithful animal"},{"partial":"b__h","expected":"buch","hint":"📖 Man liest darin","hint_translation":"You read in it"},{"partial":"h__s","expected":"haus","hint":"🏠 Wo man wohnt","hint_translation":"Where you live"},{"partial":"bl__e","expected":"blume","hint":"🌸 Wächst im Garten","hint_translation":"Grows in the garden"}]}', 4),

('de', 'A1', 'writing', 'Satz schreiben', 'Writing Sentences', 'Einfache Sätze genau abtippen', 'Type simple sentences exactly',
'{"type":"copy_sentence","instructions":"Lies den Satz und tippe ihn genau so.","exercises":[{"sentence":"Ich bin glücklich.","expected":"Ich bin glücklich.","hint":"Drei Wörter und ein Punkt","hint_translation":"Three words and a period"},{"sentence":"Die Katze ist groß.","expected":"Die Katze ist groß.","hint":"Vier Wörter über eine Katze","hint_translation":"Four words about a cat"},{"sentence":"Ich mag Rot.","expected":"Ich mag Rot.","hint":"Drei Wörter über eine Farbe","hint_translation":"Three words about a color"},{"sentence":"Sie hat einen Hund.","expected":"Sie hat einen Hund.","hint":"Vier Wörter über ein Haustier","hint_translation":"Four words about a pet"},{"sentence":"Wir gehen zur Schule.","expected":"Wir gehen zur Schule.","hint":"Vier Wörter über einen Ort","hint_translation":"Four words about a place"}]}', 5);

-- ============================================================
-- A2 GERMAN (LSRW)
-- ============================================================
INSERT INTO lessons (language_code, cefr_level, skill, title, title_translation, description, description_translation, content, order_index) VALUES
('de', 'A2', 'listening', 'Mein Alltag', 'My Daily Routine', 'Aktivitäten im Tagesablauf hören', 'Listen to activities in the daily routine',
'{"type":"listen_and_choose","instructions":"Höre den Satz und antworte.","exercises":[{"prompt":"Ich stehe jeden Morgen um sieben Uhr auf.","question":"Wann wacht die Person auf?","options":["6 Uhr","7 Uhr","8 Uhr","9 Uhr"],"correct":1},{"prompt":"Nach dem Frühstück putze ich meine Zähne.","question":"Was passiert nach dem Frühstück?","options":["Schlafen","Spielen","Zähne putzen","Fernsehen"],"correct":2},{"prompt":"Ich esse um halb eins zu Mittag.","question":"Wann gibt es Mittagessen?","options":["11:00","12:00","12:30","1:30"],"correct":2},{"prompt":"Am Abend mache ich Hausaufgaben.","question":"Wann werden die Hausaufgaben gemacht?","options":["Morgens","Mittags","Abends","Nachts"],"correct":2},{"prompt":"Ich gehe um neun Uhr ins Bett.","question":"Wann ist Schlafenszeit?","options":["8 Uhr","9 Uhr","10 Uhr","11 Uhr"],"correct":1}]}', 1),

('de', 'A2', 'speaking', 'Im Restaurant', 'At the Restaurant', 'Übe, Essen zu bestellen', 'Practice ordering food',
'{"type":"speak_and_compare","instructions":"Stell dir vor, du bist im Restaurant.","exercises":[{"prompt":"Die Speisekarte, bitte.","expected":"die speisekarte bitte","hint":"Nach der Karte fragen"},{"prompt":"Ich möchte eine Pizza, bitte.","expected":"ich möchte eine pizza bitte","hint":"Essen bestellen"},{"prompt":"Ein Wasser, bitte.","expected":"ein wasser bitte","hint":"Ein Getränk bestellen"},{"prompt":"Was kostet das?","expected":"was kostet das","hint":"Nach dem Preis fragen"},{"prompt":"Danke, es war sehr lecker!","expected":"danke es war sehr lecker","hint":"Das Essen loben"}]}', 1),

('de', 'A2', 'reading', 'Eine kurze Geschichte', 'A Short Story', 'Eine einfache Geschichte verstehen', 'Understand a simple story',
'{"type":"read_and_choose","instructions":"Lies die Geschichte und antworte.","passage":"Tom steht um sieben Uhr auf. Er isst Toast und trinkt Orangensaft zum Frühstück. Dann geht er mit seinem Freund Sam zur Schule. In der Schule lernen sie Mathe und Bio.","exercises":[{"question":"Was isst Tom zum Frühstück?","options":["Toast","Müsli","Eier","Pfannkuchen"],"correct":0},{"question":"Mit wem geht Tom zur Schule?","options":["Lehrer","Mutter","Freund Sam","Allein"],"correct":2},{"question":"Wann steht Tom auf?","options":["6 Uhr","7 Uhr","8 Uhr","9 Uhr"],"correct":1},{"question":"Was lernt er?","options":["Sport","Mathe","Kunst","Musik"],"correct":1},{"question":"Was trinkt er?","options":["Wasser","Milch","Saft","Tee"],"correct":2}]}', 1),

('de', 'A2', 'writing', 'Sätze vervollständigen', 'Completing Sentences', 'Wörter in Lücken tippen', 'Type words into gaps',
'{"type":"fill_blank_type","instructions":"Tippe das fehlende Wort.","exercises":[{"sentence":"Ich ___ jeden Tag zur Schule.","expected":"gehe","hint":"Verb für laufen","hint_translation":"Verb for walking/going"},{"sentence":"Sie ___ gestern ein rotes Kleid.","expected":"trug","hint":"Vergangenheit von tragen","hint_translation":"Past tense of wearing"},{"sentence":"Wir ___ um sieben zu Abend.","expected":"essen","hint":"Was man mit Essen macht","hint_translation":"What you do with food"},{"sentence":"Er ___ seine Hausaufgaben.","expected":"macht","hint":"Eine Tätigkeit ausführen","hint_translation":"Perform an activity"},{"sentence":"Sie ___ im Park.","expected":"spielen","hint":"Spaß haben","hint_translation":"Have fun"}]}', 1);
