-- High-quality lessons for A1 and A2 (5 exercises each with full options and hints)

-- A1 LISTENING NEW LESSONS
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A1', 'listening', 'Family Pets', 'Listen to sentences about pets', '{"type":"listen_and_choose","instructions":"Listen and choose the correct pet.","exercises":[{"prompt":"I have a cat.","options":["🐱 Cat","🐶 Dog","🐰 Rabbit","🐦 Bird"],"correct":0,"hint":"A small furry pet that says meow"},{"prompt":"I see a dog in the park.","options":["🐱 Cat","🐶 Dog","🐰 Rabbit","🐦 Bird"],"correct":1,"hint":"A loyal friend that says woof"},{"prompt":"The rabbit is hopping.","options":["🐱 Cat","🐶 Dog","🐰 Rabbit","🐦 Bird"],"correct":2,"hint":"It has long ears"},{"prompt":"The bird is singing.","options":["🐱 Cat","🐶 Dog","🐰 Rabbit","🐦 Bird"],"correct":3,"hint":"It has wings"},{"prompt":"My hamster is small.","options":["🐹 Hamster","🐘 Elephant","🦁 Lion","🦒 Giraffe"],"correct":0,"hint":"A tiny furry pet"}]}', 5),
('en', 'A1', 'listening', 'Transport', 'Identify transport modes', '{"type":"listen_and_choose","instructions":"Listen and pick the vehicle.","exercises":[{"prompt":"I ride a bus to school.","options":["🚗 Car","🚲 Bicycle","🚌 Bus","✈️ Plane"],"correct":2,"hint":"A large vehicle for many people"},{"prompt":"I fly in a plane.","options":["🚗 Car","🚲 Bicycle","🚌 Bus","✈️ Plane"],"correct":3,"hint":"It travels in the sky"},{"prompt":"My father drives a car.","options":["🚗 Car","🚲 Bicycle","🚌 Bus","✈️ Plane"],"correct":0,"hint":"A vehicle for a small family"},{"prompt":"I have a blue bicycle.","options":["🚗 Car","🚲 Bicycle","🚌 Bus","✈️ Plane"],"correct":1,"hint":"It has two wheels"},{"prompt":"The train is fast.","options":["🚂 Train","⛵ Boat","🚁 Helicopter","🚜 Tractor"],"correct":0,"hint":"It travels on tracks"}]}', 6),
('en', 'A1', 'listening', 'Weather Today', 'Listen to weather descriptions', '{"type":"listen_and_choose","instructions":"Choose the correct weather.","exercises":[{"prompt":"It is sunny today.","options":["☀️ Sunny","🌧️ Rainy","❄️ Snowy","🌩️ Stormy"],"correct":0,"hint":"The sun is shining"},{"prompt":"It is raining outside.","options":["☀️ Sunny","🌧️ Rainy","❄️ Snowy","🌩️ Stormy"],"correct":1,"hint":"Water is falling from the sky"},{"prompt":"I see snow on the ground.","options":["☀️ Sunny","🌧️ Rainy","❄️ Snowy","🌩️ Stormy"],"correct":2,"hint":"It is very cold and white"},{"prompt":"The wind is blowing.","options":["💨 Windy","☀️ Sunny","🌧️ Rainy","❄️ Snowy"],"correct":0,"hint":"Moving air"},{"prompt":"It is cloudy now.","options":["☁️ Cloudy","☀️ Sunny","🌙 Night","🌈 Rainbow"],"correct":0,"hint":"The sky is grey and full of clouds"}]}', 7),
('en', 'A1', 'listening', 'Fruit and Vegetables', 'Identify healthy foods', '{"type":"listen_and_choose","instructions":"Pick the food mentioned.","exercises":[{"prompt":"I eat a red apple.","options":["🍎 Apple","🍌 Banana","🍇 Grapes","🍊 Orange"],"correct":0,"hint":"A crunchy red fruit"},{"prompt":"The banana is yellow.","options":["🍎 Apple","🍌 Banana","🍇 Grapes","🍊 Orange"],"correct":1,"hint":"A long yellow fruit"},{"prompt":"I like sweet grapes.","options":["🍎 Apple","🍌 Banana","🍇 Grapes","🍊 Orange"],"correct":2,"hint":"Small purple or green fruit"},{"prompt":"I drink orange juice.","options":["🍎 Apple","🍌 Banana","🍇 Grapes","🍊 Orange"],"correct":3,"hint":"A round orange fruit"},{"prompt":"I eat a green carrot.","options":["🥕 Carrot","🥦 Broccoli","🌽 Corn","🍅 Tomato"],"correct":0,"hint":"Wait, carrots are usually orange, but pick the carrot icon!"}]}', 8),
('en', 'A1', 'listening', 'School Days', 'Listen to classroom items', '{"type":"listen_and_choose","instructions":"Select the correct object.","exercises":[{"prompt":"I open my book.","options":["📖 Book","🖊️ Pen","🎒 Backpack","📏 Ruler"],"correct":0,"hint":"You read this"},{"prompt":"I write with a pen.","options":["📖 Book","🖊️ Pen","🎒 Backpack","📏 Ruler"],"correct":1,"hint":"Used for writing"},{"prompt":"My backpack is heavy.","options":["📖 Book","🖊️ Pen","🎒 Backpack","📏 Ruler"],"correct":2,"hint":"You carry your things in this"},{"prompt":"I use a ruler in math.","options":["📖 Book","🖊️ Pen","🎒 Backpack","📏 Ruler"],"correct":3,"hint":"Used to measure things"},{"prompt":"The teacher has a pencil.","options":["✏️ Pencil","🖥️ Computer","📓 Notebook","💺 Chair"],"correct":0,"hint":"Used for drawing or writing"}]}', 9);

-- A2 LISTENING NEW LESSONS
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A2', 'listening', 'Fun Weekends', 'Listen to weekend activities', '{"type":"listen_and_choose","instructions":"Choose the activity.","exercises":[{"prompt":"I will go to the beach with my family.","options":["🏖️ Beach","⛰️ Mountains","Camping","Stadium"],"correct":0,"hint":"They are going to the sea"},{"prompt":"I am going to play soccer on Saturday.","options":["⚽ Soccer","🏀 Basketball","🎾 Tennis","🏈 Football"],"correct":0,"hint":"A popular sport with a round ball"},{"prompt":"We are watching a movie at the cinema.","options":["🎬 Cinema","🎭 Theater","🏟️ Stadium","🏫 School"],"correct":0,"hint":"A place for films"},{"prompt":"I like to swim in the pool.","options":["🏊 Swimming","🚴 Cycling","🏃 Running","🚶 Walking"],"correct":0,"hint":"An activity in water"},{"prompt":"They are going to a birthday party.","options":["🎂 Party","🏢 Office","🏥 Hospital","🏦 Bank"],"correct":0,"hint":"A celebration with cake"}]}', 5),
('en', 'A2', 'listening', 'Travel Destinations', 'Identify travel spots', '{"type":"listen_and_choose","instructions":"Pick the correct place.","exercises":[{"prompt":"I want to visit Paris and see the Eiffel Tower.","options":["🗼 Paris","🗽 New York","🏰 London","🕌 Dubai"],"correct":0,"hint":"A famous city in France"},{"prompt":"We are going to New York to see the Statue of Liberty.","options":["🗼 Paris","🗽 New York","🏰 London","🕌 Dubai"],"correct":1,"hint":"A famous city in the USA"},{"prompt":"I would love to see the Big Ben in London.","options":["🗼 Paris","🗽 New York","🏰 London","🕌 Dubai"],"correct":2,"hint":"The capital of the UK"},{"prompt":"The Burj Khalifa is in Dubai.","options":["🗼 Paris","🗽 New York","🏰 London","🕌 Dubai"],"correct":3,"hint":"A city with very tall buildings"},{"prompt":"I am visiting Tokyo next month.","options":["🇯🇵 Tokyo","🇮🇳 Delhi","🇦🇺 Sydney","🇧🇷 Rio"],"correct":0,"hint":"The capital of Japan"}]}', 6),
('en', 'A2', 'listening', 'At the Market', 'Listen to items to buy', '{"type":"listen_and_choose","instructions":"Select the item.","exercises":[{"prompt":"I need to buy a bottle of milk.","options":["🥛 Milk","🍎 Apple","🍞 Bread","🧀 Cheese"],"correct":0,"hint":"A white drink for breakfast"},{"prompt":"Can you get some fresh bread?","options":["🥛 Milk","🍎 Apple","🍞 Bread","🧀 Cheese"],"correct":2,"hint":"Made at a bakery"},{"prompt":"I will buy three red tomatoes.","options":["🍅 Tomato","🧅 Onion","🥔 Potato","🥕 Carrot"],"correct":0,"hint":"Used in salad and soup"},{"prompt":"Do we need any eggs?","options":["🥚 Eggs","🥓 Bacon","🌭 Sausage","🥞 Pancake"],"correct":0,"hint":"Chickens lay these"},{"prompt":"I want to buy some chocolate.","options":["🍫 Chocolate","🍬 Candy","🍦 Ice Cream","🍪 Cookie"],"correct":0,"hint":"A sweet brown treat"}]}', 7),
('en', 'A2', 'listening', 'Party Decorations', 'Identify party elements', '{"type":"listen_and_choose","instructions":"Choose the correct part of the party.","exercises":[{"prompt":"The chocolate cake is delicious.","options":["🎂 Cake","🎉 Popper","🎈 Balloon","🎁 Gift"],"correct":0,"hint":"The main sweet food at a party"},{"prompt":"Look at all the colorful balloons!","options":["🎂 Cake","🎉 Popper","🎈 Balloon","🎁 Gift"],"correct":2,"hint":"Floating decorations"},{"prompt":"I have a big gift for you.","options":["🎂 Cake","🎉 Popper","🎈 Balloon","🎁 Gift"],"correct":3,"hint":"A present in a box"},{"prompt":"The music is very loud.","options":["🎵 Music","🔦 Light","🍕 Food","🥤 Drink"],"correct":0,"hint":"Something you hear"},{"prompt":"Everyone is wearing party hats.","options":["🥳 Party Hat","👓 Glasses","🧣 Scarf","🧤 Gloves"],"correct":0,"hint":"Used to celebrate"}]}', 8),
('en', 'A2', 'listening', 'Keeping Healthy', 'Listen to health advice', '{"type":"listen_and_choose","instructions":"Pick the healthy choice.","exercises":[{"prompt":"You should drink eight glasses of water every day.","options":["💧 Water","☕ Coffee","🍔 Burger","🍟 Fries"],"correct":0,"hint":"Essential for life"},{"prompt":"Exercising daily is good for your body.","options":["🏃 Running","📺 TV","🚗 Driving","🎮 Gaming"],"correct":0,"hint":"Being active"},{"prompt":"Eating vegetables makes you strong.","options":["🥦 Broccoli","🍕 Pizza","🍩 Donut","🍫 Chocolate"],"correct":0,"hint":"Healthy green food"},{"prompt":"You need to sleep for eight hours.","options":["😴 Sleep","🎤 Sing","💃 Dance","🏢 Work"],"correct":0,"hint":"Resting at night"},{"prompt":"Remember to wash your hands.","options":["🧼 Soap","📱 Phone","🔑 Key","🖊️ Pen"],"correct":0,"hint":"Important for hygiene"}]}', 9);

-- A1 SPEAKING NEW LESSONS
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A1', 'speaking', 'I Like Food', 'Talk about favorite food', '{"type":"speak_and_compare","instructions":"Listen and repeat the sentence clearly.","exercises":[{"prompt":"I love pizza.","expected":"i love pizza","hint":"A round flat bread with toppings"},{"prompt":"I like sweet apples.","expected":"i like sweet apples","hint":"A red or green fruit"},{"prompt":"I eat bread and butter.","expected":"i eat bread and butter","hint":"A common breakfast"},{"prompt":"Ice cream is cold.","expected":"ice cream is cold","hint":"A frozen dessert"},{"prompt":"I drink fresh milk.","expected":"i drink fresh milk","hint":"A white drink from cows"}]}', 6),
('en', 'A1', 'speaking', 'My Day', 'Describe daily activities', '{"type":"speak_and_compare","instructions":"Speak the daily routine sentences.","exercises":[{"prompt":"I wake up at seven.","expected":"i wake up at seven","hint":"Starting your day"},{"prompt":"I brush my white teeth.","expected":"i brush my white teeth","hint":"Part of morning hygiene"},{"prompt":"I put on my shoes.","expected":"i put on my shoes","hint":"Getting ready to go out"},{"prompt":"I go to school now.","expected":"i go to school now","hint":"Leaving for class"},{"prompt":"I come home at four.","expected":"i come home at four","hint":"Ending your school day"}]}', 7),
('en', 'A1', 'speaking', 'The Weather', 'Talk about the weather', '{"type":"speak_and_compare","instructions":"Repeat the weather sentences.","exercises":[{"prompt":"It is a sunny day.","expected":"it is a sunny day","hint":"When the sun is out"},{"prompt":"It is raining today.","expected":"it is raining today","hint":"When the sky is wet"},{"prompt":"The sky is blue.","expected":"the sky is blue","hint":"A clear day"},{"prompt":"It is very cold.","expected":"it is very cold","hint":"When you need a jacket"},{"prompt":"The wind is strong.","expected":"the wind is strong","hint":"When the air moves fast"}]}', 8),
('en', 'A1', 'speaking', 'Introduce Family', 'Talk about family members', '{"type":"speak_and_compare","instructions":"Say the sentences about your family.","exercises":[{"prompt":"This is my brother.","expected":"this is my brother","hint":"A male sibling"},{"prompt":"This is my kind mother.","expected":"this is my kind mother","hint":"A female parent"},{"prompt":"I have a small sister.","expected":"i have a small sister","hint":"A female sibling"},{"prompt":"My father is tall.","expected":"my father is tall","hint":"A male parent"},{"prompt":"I love my family.","expected":"i love my family","hint":"A warm feeling"}]}', 9),
('en', 'A1', 'speaking', 'Colors Everywhere', 'Name colors in sentences', '{"type":"speak_and_compare","instructions":"Say the color names in sentences.","exercises":[{"prompt":"The bright sky is blue.","expected":"the bright sky is blue","hint":"🔵"},{"prompt":"The fresh grass is green.","expected":"the fresh grass is green","hint":"🟢"},{"prompt":"The big sun is yellow.","expected":"the big sun is yellow","hint":"🟡"},{"prompt":"The sweet apple is red.","expected":"the sweet apple is red","hint":"🔴"},{"prompt":"The small orange is orange.","expected":"the small orange is orange","hint":"🟠"}]}', 10);

-- A2 SPEAKING NEW LESSONS
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A2', 'speaking', 'My Next Trip', 'Discuss travel plans', '{"type":"speak_and_compare","instructions":"Practice speaking about future travel.","exercises":[{"prompt":"I will visit London next year.","expected":"i will visit london next year","hint":"Planning a trip"},{"prompt":"I want to see the mountains.","expected":"i want to see the mountains","hint":"A high place"},{"prompt":"I will fly by plane.","expected":"i will fly by plane","hint":"Mode of transport"},{"prompt":"I am packing my suitcase.","expected":"i am packing my suitcase","hint":"Getting ready to travel"},{"prompt":"It will be a long flight.","expected":"it will be a long flight","hint":"Spending time in the air"}]}', 4),
('en', 'A2', 'speaking', 'Shopping List', 'Practice shopping dialogue', '{"type":"speak_and_compare","instructions":"Say these shopping phrases.","exercises":[{"prompt":"How much is this shirt?","expected":"how much is this shirt","hint":"Asking for the price"},{"prompt":"I would like two red apples.","expected":"i would like two red apples","hint":"Ordering fruit"},{"prompt":"Do you have any fresh milk?","expected":"do you have any fresh milk","hint":"Asking for a product"},{"prompt":"I will pay with my card.","expected":"i will pay with my card","hint":"Payment method"},{"prompt":"Where is the supermarket?","expected":"where is the supermarket","hint":"Asking for location"}]}', 5),
('en', 'A2', 'speaking', 'Healthy Living', 'Give health advice', '{"type":"speak_and_compare","instructions":"Speak these health tips.","exercises":[{"prompt":"Drink more water every day.","expected":"drink more water every day","hint":"Good for hydration"},{"prompt":"Eat fresh fruit and vegetables.","expected":"eat fresh fruit and vegetables","hint":"Proper nutrition"},{"prompt":"Go for a run in the park.","expected":"go for a run in the park","hint":"Physical exercise"},{"prompt":"Get enough sleep every night.","expected":"get enough sleep every night","hint":"Essential for rest"},{"prompt":"Avoid too much sugar.","expected":"avoid too much sugar","hint":"Health warning"}]}', 6),
('en', 'A2', 'speaking', 'Birthday Party', 'Talk about celebrations', '{"type":"speak_and_compare","instructions":"Speak these party sentences.","exercises":[{"prompt":"Happy birthday to my friend!","expected":"happy birthday to my friend","hint":"A celebration"},{"prompt":"I am bringing a big gift.","expected":"i am bringing a big gift","hint":"A present"},{"prompt":"We will eat chocolate cake.","expected":"we will eat chocolate cake","hint":"A sweet treat"},{"prompt":"The party starts at five.","expected":"the party starts at five","hint":"The time"},{"prompt":"I hope you enjoy your day.","expected":"i hope you enjoy your day","hint":"Well-wishes"}]}', 7),
('en', 'A2', 'speaking', 'Weekend Fun', 'Talk about weekend plans', '{"type":"speak_and_compare","instructions":"Discuss your weekend.","exercises":[{"prompt":"I will go hiking on Saturday.","expected":"i will go hiking on saturday","hint":"Outdoor activity"},{"prompt":"I plan to read a new book.","expected":"i plan to read a new book","hint":"Relaxation"},{"prompt":"We are meeting for coffee.","expected":"we are meeting for coffee","hint":"Social activity"},{"prompt":"I will visit my grandparents.","expected":"i will visit my grandparents","hint":"Family time"},{"prompt":"The weekend was very fun.","expected":"the weekend was very fun","hint":"Summarizing"}]}', 8);

-- A1 READING NEW LESSONS
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A1', 'reading', 'Name the Animals', 'Read and match animals', '{"type":"read_and_choose","instructions":"Read the word and pick the matching icon.","exercises":[{"question":"Cat","options":["🐱 Cat","🐶 Dog","🐰 Rabbit","🐦 Bird"],"correct":0},{"question":"Dog","options":["🐱 Cat","🐶 Dog","🐰 Rabbit","🐦 Bird"],"correct":1},{"question":"Rabbit","options":["🐱 Cat","🐶 Dog","🐰 Rabbit","🐦 Bird"],"correct":2},{"question":"Bird","options":["🐱 Cat","🐶 Dog","🐰 Rabbit","🐦 Bird"],"correct":3},{"question":"Hamster","options":["🐹 Hamster","🐘 Elephant","🦁 Lion","🦒 Giraffe"],"correct":0}]}', 6),
('en', 'A1', 'reading', 'Color Reading', 'Read color words', '{"type":"read_and_choose","instructions":"Match the word to the color circle.","exercises":[{"question":"Red","options":["🔴 Red","🔵 Blue","🟢 Green","🟡 Yellow"],"correct":0},{"question":"Blue","options":["🔴 Red","🔵 Blue","🟢 Green","🟡 Yellow"],"correct":1},{"question":"Green","options":["🔴 Red","🔵 Blue","🟢 Green","🟡 Yellow"],"correct":2},{"question":"Yellow","options":["🔴 Red","🔵 Blue","🟢 Green","🟡 Yellow"],"correct":3},{"question":"Orange","options":["🟠 Orange","🟣 Purple","⚫ Black","⚪ White"],"correct":0}]}', 7),
('en', 'A1', 'reading', 'Short Stories 1', 'Read short story fragments', '{"type":"read_and_choose","instructions":"Answer the question about the text.","passage":"Tom has a big red ball. He plays in the park with his friend Sam.","exercises":[{"question":"What does Tom have?","options":["A ball","A cat","A book","A pen"],"correct":0},{"question":"Where does Tom play?","options":["Park","School","Home","Mall"],"correct":0},{"question":"Who is with Tom?","options":["Sam","Mom","Dad","Teacher"],"correct":0},{"question":"What color is the ball?","options":["Red","Blue","Green","Yellow"],"correct":0},{"question":"Is the ball small?","options":["No, it is big","Yes","I don''t know","Maybe"],"correct":0}]}', 8),
('en', 'A1', 'reading', 'Food Words', 'Read health food items', '{"type":"read_and_choose","instructions":"Match the food word to its icon.","exercises":[{"question":"Apple","options":["🍎 Apple","🍌 Banana","🍇 Grapes","🍊 Orange"],"correct":0},{"question":"Banana","options":["🍎 Apple","🍌 Banana","🍇 Grapes","🍊 Orange"],"correct":1},{"question":"Bread","options":["🍞 Bread","🥖 Baguette","🥐 Croissant","🍰 Cake"],"correct":0},{"question":"Milk","options":["🥛 Milk","🥤 Juice","☕ Coffee","🍷 Wine"],"correct":0},{"question":"Chocolate","options":["🍫 Chocolate","🍬 Candy","🍦 Ice Cream","🍪 Cookie"],"correct":0}]}', 9),
('en', 'A1', 'reading', 'Class Objects', 'Identify school items', '{"type":"read_and_choose","instructions":"Match the object word to its icon.","exercises":[{"question":"Book","options":["📖 Book","🖊️ Pen","🎒 Backpack","📏 Ruler"],"correct":0},{"question":"Pen","options":["📖 Book","🖊️ Pen","🎒 Backpack","📏 Ruler"],"correct":1},{"question":"Ruler","options":["📖 Book","🖊️ Pen","🎒 Backpack","📏 Ruler"],"correct":3},{"question":"Backpack","options":["📖 Book","🖊️ Pen","🎒 Backpack","📏 Ruler"],"correct":2},{"question":"Pencil","options":["✏️ Pencil","🖥️ Computer","📓 Notebook","💺 Chair"],"correct":0}]}', 10);

-- A2 READING NEW LESSONS
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A2', 'reading', 'Travel Story', 'Read a travel narrative', '{"type":"read_and_choose","instructions":"Answer questions about Anna''s trip.","passage":"Anna flew to Paris last summer. She visited the Eiffel Tower and ate many delicious croissants. The weather was sunny every day.","exercises":[{"question":"Where did Anna go?","options":["London","Paris","Rome","Berlin"],"correct":1},{"question":"When did she go?","options":["Last summer","Last winter","Last week","Yesterday"],"correct":0},{"question":"What did she see?","options":["Statue of Liberty","Eiffel Tower","Big Ben","Colosseum"],"correct":1},{"question":"What did she eat?","options":["Pizza","croissants","Salad","Pasta"],"correct":1},{"question":"What was the weather like?","options":["Rainy","Sunny","Cloudy","Snowy"],"correct":1}]}', 4),
('en', 'A2', 'reading', 'Shopping Day', 'Read a shopping conversation', '{"type":"read_and_choose","instructions":"Answer questions about the shopping trip.","passage":"Mike went to the supermarket. He bought five red apples and a bottle of fresh milk. He paid with his bank card and went home to cook.","exercises":[{"question":"What did Mike buy first?","options":["Bread","Apples","Cheese","Milk"],"correct":1},{"question":"How many apples?","options":["Three","Four","Five","Six"],"correct":2},{"question":"What color were the apples?","options":["Green","Yellow","Red","Orange"],"correct":2},{"question":"How did he pay?","options":["Cash","Bank card","Phone","He didn''t pay"],"correct":1},{"question":"What did he do at home?","options":["Sleep","Watch TV","Cook","Read"],"correct":2}]}', 5),
('en', 'A2', 'reading', 'A Birthday Note', 'Read a birthday message', '{"type":"read_and_choose","instructions":"Comprehend the birthday note.","passage":"Dear Sam, Happy Birthday! I hope you have a wonderful day. I have a surprise gift for you. See you at the party at 5 PM! Love, Anna.","exercises":[{"question":"Who is the note for?","options":["Sam","Tom","Anna","Mike"],"correct":0},{"question":"Who wrote the note?","options":["Sam","Anna","Teacher","Mom"],"correct":1},{"question":"What does Anna have for Sam?","options":["A book","A surprise gift","A card","Nothing"],"correct":1},{"question":"What time is the party?","options":["3 PM","4 PM","5 PM","6 PM"],"correct":2},{"question":"What is the event?","options":["A school day","A birthday","A trip","A movie"],"correct":1}]}', 6),
('en', 'A2', 'reading', 'Health Guide', 'Read health advice', '{"type":"read_and_choose","instructions":"Determine if the health tip is correct.","exercises":[{"question":"Drink eight glasses of water daily.","options":["True","False"],"correct":0},{"question":"It is good to sleep only 2 hours.","options":["True","False"],"correct":1},{"question":"Vegetables make you healthy.","options":["True","False"],"correct":0},{"question":"Chocolate is better than fruit.","options":["True","False"],"correct":1},{"question":"Executive exercise is important.","options":["True","False"],"correct":0}]}', 7),
('en', 'A2', 'reading', 'Weekend Life', 'Read about weekend activities', '{"type":"read_and_choose","instructions":"Finalize the weekend plans.","exercises":[{"question":"Go hiking in the mountains.","options":["Yes","No"],"correct":0},{"question":"Working in the office all day.","options":["Yes","No"],"correct":1},{"question":"Reading a book on the sofa.","options":["Yes","No"],"correct":0},{"question":"Running a marathon.","options":["Yes","No"],"correct":1},{"question":"Eating dinner with family.","options":["Yes","No"],"correct":0}]}', 8);

-- A1 WRITING NEW LESSONS
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A1', 'writing', 'Spell the Colors', 'Type color names correctly', '{"type":"type_word","instructions":"Type the name of the color you see.","exercises":[{"prompt":"🔴","expected":"Red","hint":"The color of fire"},{"prompt":"🔵","expected":"Blue","hint":"The color of the sky"},{"prompt":"🟢","expected":"Green","hint":"The color of grass"},{"prompt":"🟡","expected":"Yellow","hint":"The color of the sun"},{"prompt":"🟠","expected":"Orange","hint":"A fruit has this name too"}]}', 6),
('en', 'A1', 'writing', 'Animal Names', 'Type animal names correctly', '{"type":"type_word","instructions":"Type the animal name for the icon.","exercises":[{"prompt":"🐱","expected":"Cat","hint":"Meow"},{"prompt":"🐶","expected":"Dog","hint":"Woof"},{"prompt":"🐦","expected":"Bird","hint":"Tweet"},{"prompt":"🐟","expected":"Fish","hint":"Blub"},{"prompt":"🐘","expected":"Elephant","hint":"A very big animal"}]}', 7),
('en', 'A1', 'writing', 'Copy Short Sentences', 'Practice writing full sentences', '{"type":"copy_sentence","instructions":"Copy the sentence exactly as shown.","exercises":[{"sentence":"I have a small ball.","expected":"I have a small ball.","hint":"Copy carefully"},{"sentence":"The cat is very happy.","expected":"The cat is very happy.","hint":"Copy carefully"},{"sentence":"I like to eat pizza.","expected":"I like to eat pizza.","hint":"Copy carefully"},{"sentence":"She has a big dog.","expected":"She has a big dog.","hint":"Copy carefully"},{"sentence":"We go to school now.","expected":"We go to school now.","hint":"Copy carefully"}]}', 8),
('en', 'A1', 'writing', 'Fill the Gaps', 'Complete simple sentences', '{"type":"fill_blank","instructions":"Choose the correct word to fill the gap.","exercises":[{"sentence":"I ___ a new cat.","options":["have","has","had","having"],"correct":0},{"sentence":"She ___ very happy.","options":["is","are","am","be"],"correct":0},{"sentence":"They ___ to the park.","options":["go","goes","going","gone"],"correct":0},{"sentence":"The sky ___ blue today.","options":["is","are","am","be"],"correct":0},{"sentence":"We ___ breakfast now.","options":["eat","eats","eating","ate"],"correct":0}]}', 9),
('en', 'A1', 'writing', 'Type the Numbers', 'Practice spelling numbers', '{"type":"type_word","instructions":"Type the word for the number.","exercises":[{"prompt":"1","expected":"One","hint":"Starting number"},{"prompt":"2","expected":"Two","hint":"After one"},{"prompt":"3","expected":"Three","hint":"After two"},{"prompt":"4","expected":"Four","hint":"After three"},{"prompt":"5","expected":"Five","hint":"After four"}]}', 10);

-- A2 WRITING NEW LESSONS
INSERT INTO lessons (language_code, cefr_level, skill, title, description, content, order_index) VALUES
('en', 'A2', 'writing', 'Travel Diary', 'Write about a holiday trip', '{"type":"guided_writing","instructions":"Answer the questions about your trip.","exercises":[{"question":"Where did you go?","starter":"I went to ","example":"I went to Paris.","hint":"Name a city"},{"question":"What did you see?","starter":"I saw ","example":"I saw the Eiffel Tower.","hint":"Mention a landmark"},{"question":"What did you eat?","starter":"I ate ","example":"I ate croissants and fruit.","hint":"Mention some food"},{"question":"How was the weather?","starter":"The weather was ","example":"The weather was sunny and hot.","hint":"Describe the sky"},{"question":"Did you like it?","starter":"I liked it because ","example":"I liked it because it was beautiful.","hint":"Give a reason"}]}', 4),
('en', 'A2', 'writing', 'Hobby Description', 'Write about things you enjoy', '{"type":"guided_writing","instructions":"Describe your favorite hobby.","exercises":[{"question":"What is your favorite hobby?","starter":"My favorite hobby is ","example":"My favorite hobby is painting.","hint":"Name the activity"},{"question":"When do you do it?","starter":"I do it on ","example":"I do it on weekends.","hint":"Mention a time"},{"question":"Who do you do it with?","starter":"I do it with ","example":"I do it with my friends.","hint":"Mention people"},{"question":"Why do you like it?","starter":"I like it because ","example":"I like it because it is fun.","hint":"Give a reason"},{"question":"Where do you do it?","starter":"I do it in ","example":"I do it in the park.","hint":"Mention a place"}]}', 5),
('en', 'A2', 'writing', 'Write a Letter', 'Practice formal writing basics', '{"type":"guided_writing","instructions":"Finish the short letter.","exercises":[{"question":"How do you start a letter?","starter":"Dear ","example":"Dear Sam,","hint":"Add a name"},{"question":"What is the first question?","starter":"How are ","example":"How are you today?","hint":"Ask how they are"},{"question":"Mention a plan?","starter":"I want to ","example":"I want to visit you.","hint":"State an intention"},{"question":"Ask for a reply?","starter":"Please ","example":"Please write back soon.","hint":"A polite request"},{"question":"How do you end a letter?","starter":"Love, ","example":"Love, Anna.","hint":"Closing and name"}]}', 6),
('en', 'A2', 'writing', 'Food Review', 'Write about a meal', '{"type":"guided_writing","instructions":"Describe your favorite food.","exercises":[{"question":"What is your favorite food?","starter":"My favorite food is ","example":"My favorite food is sushi.","hint":"Name the dish"},{"question":"What is in it?","starter":"It has ","example":"It has fish and rice.","hint":"List ingredients"},{"question":"When do you eat it?","starter":"I eat it for ","example":"I eat it for dinner.","hint":"Mention a mealtime"},{"question":"Why?","starter":"Because ","example":"Because it is very tasty.","hint":"Give a reason"},{"question":"Where can you buy it?","starter":"I buy it at ","example":"I buy it at the restaurant.","hint":"Mention a place"}]}', 7),
('en', 'A2', 'writing', 'Plans for Future', 'Write about what you will do', '{"type":"guided_writing","instructions":"Write about your future intentions.","exercises":[{"question":"What will you do next summer?","starter":"I will ","example":"I will travel to Spain.","hint":"Mention an action"},{"question":"Where will you go?","starter":"I will go to ","example":"I will go to the beach.","hint":"Mention a place"},{"question":"What will you buy?","starter":"I will buy ","example":"I will buy a new bike.","hint":"Mention an item"},{"question":"Who will be with you?","starter":"I will be with ","example":"I will be with my cousins.","hint":"Mention people"},{"question":"How do you feel?","starter":"I feel ","example":"I feel very excited.","hint":"Describe an emotion"}]}', 8);
